### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by k25jlj** [SanAndreasP/ClaySoldiersMod#102]
Game is crashing with SAPManPack-1.7.10-2.5.1 and ClaySoldiersMod-1.7.10-2.0.0-beta.2 in the mods folder.  

fml-client-latest.log  file:

https://gist.github.com/k25jlj/dc404d2ee7ec437f2645

**Comment by SanAndreasP** [comment]
Sorry, but I don't see anything out of order here...
Can you give me the launcher output?

**Comment by k25jlj** [comment]
Minecraft makes it through the page with the forge graphic in the bottom right corner - loading clay soldiers, however it is followed by a blank black screen.  The minecraft music is in the background.
I've included the launcher output prior to clicking play. 
Is the launcher output (after clicking play) saved somewhere?
Thanks 


     On Thursday, June 25, 2015 7:57 AM, SanAndreasP <notifications@github.com> wrote:
   

 Sorry, but I don't see anything out of order here...
Can you give me the launcher output?—

**Comment by SanAndreasP** [comment]
I don't think so...
Does it boot up with only Forge (so w/o my mods)?

**Comment by k25jlj** [comment]
No, it does the same thing. 


     On Friday, June 26, 2015 11:35 AM, SanAndreasP <notifications@github.com> wrote:
   

 I don't think so...
Does it boot up with only Forge (so w/o my mods)?—

**Comment by SanAndreasP** [comment]
If it's not even booting up w/o my mods, then this is a problem with your Forge installation itself.
You need to report it on their forums: http://www.minecraftforgen.net
They may be able to help you. Other than that, in this case I can't help you, sorry.
