### ISSUE TITLE
Transparent Hand with Clay Soldiers and Project Red Mod.

### ISSUE THREAD

**Issue by GamerM** [SanAndreasP/ClaySoldiersMod#104]
The mod Project Red 4.7.0pre2.87 and Clay Soldiers makes a weird bug. If you run both mods at the same time. It will make your hand transparent. Is there any way you can fix this? Ask me if you need a log and I'm also going to report this issue to the creators of project red. Thanks!

Proof that it does make your hand transparent:
![2015-06-24_11 55 10](https://cloud.githubusercontent.com/assets/8530902/8356500/c1e465f6-1b23-11e5-8ee5-62738f030239.png)

**Comment by SanAndreasP** [comment]
You say both mods, so if you're running ProjectRed on its own it doesn't happen?

**Comment by GamerM** [comment]
Yes it doesn't happen. Only if they are running together.

**Comment by SanAndreasP** [comment]
Another question: Does it happen w/o Clay Soldiers? I meant just ProjectRed and my Manager Pack?

**Comment by GamerM** [comment]
It works completely fine with just your my manager pack. I tested it out already.

**Comment by SanAndreasP** [comment]
hm, so something in the mod is screwing with the GL state in combination with ProjectRed...
I'll look into it.

**Comment by GamerM** [comment]
Thanks San! You're the best! :)

**Comment by SanAndreasP** [comment]
I found the error, the ParticleRenderDispatcher included in the ClaySoldiersMod seems to leak a GL state. Fortunately my Manager Pack comes now with its own (which does work with ProjectRed), so I'll make the code use that instead.

**Comment by GamerM** [comment]
Ok. I'll close the issue on the project red side so that they don't do anything else to it. Thanks SanAndresasP for your work on fixing the bug. You can close the issue when you're done with the patch.
