### ISSUE TITLE
able to fight with them?

### ISSUE THREAD

**Issue by dude98** [SanAndreasP/ClaySoldiersMod#112]
i always wanted to try and fight with my cyans, but i can only go clay cam, when i use morph mod to be one, i still one hit kill the enemy. i want to know if there was a way you could make your character a clay soldier to fight on their side

**Comment by dude98** [comment]
also, is there a way to make them a home with a working door? the way i set it up was a slab and a trapdoor. if you can figure something out, tell me. thanks!

**Comment by Spartan322** [comment]
don't hijack issues (even if their your own), also refer #20

**Comment by SanAndreasP** [comment]
@Spartan322 referenced you the issues you need to look at.

**Comment by dude98** [comment]
i never looked at the others until now so i didn't know
