### ISSUE TITLE
Which java should I install for mac to run the mod?

### ISSUE THREAD

**Issue by guancialee** [SanAndreasP/ClaySoldiersMod#114]
I'm having a really hard time figuring out how to install this mod. Based on sanandreas comments it looks like java 6 and 8 don't work for this mod. After downloading minecraft I'm prompted "To open 'Minecraft' you need to install a Java SE 6 Runtime" with an install button. Additionally there is Java SDK and i'm not sure if i'm supposed to download that one or a different one for this mod to work.

**Comment by SanAndreasP** [comment]
Java 8 works fine. Java 6 doesn't, because we use Java 7 specific features.
See #67 for how to get it working with J7 or higher on mac.
