### ISSUE TITLE
crashed on mac

### ISSUE THREAD

**Issue by Fredodo82** [SanAndreasP/ClaySoldiersMod#115]
your mod crashes on the client but not on my server ( on mac)
So my problem is not with the java java 6 because I board her 8 proves that I was right

**Comment by nascarfan013** [comment]
I have the same problem

**Comment by SanAndreasP** [comment]
The server uses on-board java, it doesn't ship any java, the client uses the launcher, which ships Java 6 by default, that's where #67 comes into play...

If you REALLY can't get it to work in any way, I can only suggest using a custom launcher like MultiMC:
https://multimc.org/
