### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by nascarfan013** [SanAndreasP/ClaySoldiersMod#118]
Whenever i place down more than 1 group of soldiers in the same block space, everything goes black. I have Java 8 and other than this bug the mod works fine.

**Comment by SanAndreasP** [comment]
Please post logs (.minecraft/logs/fml-client-latest.log) via http://gist.github.com

**Comment by nascarfan013** [comment]
https://gist.github.com/nascarfan013/5fecdf8d7fa597d835d1

The link to the log is above.

**Comment by SanAndreasP** [comment]
this is not the correct log, I'm afraid.
I need the file called "fml-client-latest.log"

**Comment by nascarfan013** [comment]
It seems to put me in some sort of spectator mode now. Does not blacken the entire screen anymore. BTW i made a stadium for the clay soldiers is it ok if i make it public?

**Comment by SanAndreasP** [comment]
sure, but I still need the correct logs.

**Comment by nascarfan013** [comment]
https://gist.github.com/nascarfan013/481e99c647d018b2b99b

i belive this is the log you are looking for.

**Comment by SanAndreasP** [comment]
Yes. I don't see any error in there, though <.<

So the only thing I can suggest is just running CSM without any mods beside it installed, so just having CSM and the ManagerPack. No NEI, No CodeChickenCore, No CustomNPCs.

**Comment by nascarfan013** [comment]
ok
