### ISSUE TITLE
I have an Idea

### ISSUE THREAD

**Issue by nascarfan013** [SanAndreasP/ClaySoldiersMod#119]
How about different classes of soldiers being able to be assigned. Like if you added miniature weapons some soldiers could be warriors while others could be archers, each class having their style of fighting. Maybe these could be decided at the nexus or by dropping a miniature weapon.

**Comment by SanAndreasP** [comment]
archer = give them ranged weapons
warrior = give them meelee weapons
tank = give them a diamond
mage = give them any kind of "magical" item (emerald, quartz)

**Comment by SanAndreasP** [comment]
Since there's no response to this in over a month, I'll close this. If you have any other issue/problem/question, open up a new issue.
