### ISSUE TITLE
why you deleted ?

### ISSUE THREAD

**Issue by Fredodo82** [SanAndreasP/ClaySoldiersMod#122]
1 soldier takes the items in the trunk
2 he built
im dowload clay soldier master and ?

**Comment by Spartan322** [comment]
Please close this, this has been explained multiple times, the mod was started fresh in 1.7.10, so some previous feature are still missing.

**Comment by Fredodo82** [comment]
i ave dowload clay soldier master

**Comment by Spartan322** [comment]
It is not implemented, don't you remember that the mod was recreated. This is suppose to be implemented later

**Comment by SanAndreasP** [comment]
because the mod is not finished yet <.<
Also, next time you have an issue, search for it beforehand, this exact issue was posted already at #17
