### ISSUE TITLE
Clay soldier master ?

### ISSUE THREAD

**Issue by Fredodo82** [SanAndreasP/ClaySoldiersMod#123]
his greenhouse what?

**Comment by Fredodo82** [comment]
I go to # 17 but he told me to go on auttre # 2 ** then re going to # 17

**Comment by SanAndreasP** [comment]
wut?

**Comment by Fredodo82** [comment]
Sorry google translation didnt managed to translate: wut?

**Comment by Fredodo82** [comment]
I board download, I board view: updat build
https://github.com/SanAndreasP/ClaySoldiersMod

**Comment by Spartan322** [comment]
This needs to be closed, spamming is annoying on github

**Comment by SanAndreasP** [comment]
Google Translate is not good to communicate with us... I'm sorry, I can't understand half of what you're saying. So either get someone who knows english as well as your native language or learn english yourself.

Also you spam the issue tracker with useless questions...
I'm warning you now, If you continue to do this, I have to ban you for a week...
You can still post on issues even if they're closed! You can still post if you encounter any bug you've noticed AND it's not already in the issue tracker (search for it beforehand). Same goes for crashes.

Other than that, there's the forum thread you can discuss ANYTHING else over here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280625-clay-soldiers-mod-v-2-0-0-beta-2

**Comment by Fredodo82** [comment]
im dowload ClaySoldiersMod-master.rar 
put in mods folder ?

**Comment by Fredodo82** [comment]
im clic download.zip
https://github.com/SanAndreasP/ClaySoldiersMod
And ?????????????????????????????????????????

**Comment by SanAndreasP** [comment]
what are you trying to do?

**Comment by SanAndreasP** [comment]
What you have here is a ZIP package of the repo, nothing more

**Comment by Fredodo82** [comment]
why are brand: updat build?

**Comment by SanAndreasP** [comment]
Sorry, this repo code is for modders and coders who want to contribute or just look at the code, not for the regular user like you (except for the issue tracker). You can find all the downloads you'll ever need over the forum thread:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280625-clay-soldiers-mod-v-2-0-0-beta-2
