### ISSUE TITLE
Crashing: Re

### ISSUE THREAD

**Issue by Tykle2002** [SanAndreasP/ClaySoldiersMod#125]
To prove that I do have the latest version of java...
![screen shot 2015-08-10 at 9 47 06 pm](https://cloud.githubusercontent.com/assets/13716271/9172862/e6dbae4c-3fa8-11e5-96b3-8cd3d2735088.png)

**Comment by SanAndreasP** [comment]
Don't tell me it isn't, it clearly states it is. <tt>Unsupported major.minor version 51.0</tt>
#67, read that. All of it. Then come back if you still have issues.

I won't tell you again.

The Minecraft Launcher for mac doesn't give 2 craps about your installed java version. You need to force it to use your installed Java or else it will use the version shipped with the launcher. The issue I've linked has links which explain how to do that.
Also you can reply to closed issues just fine, no need to open the exact same issue twice.
