### ISSUE TITLE
Can you give me some hints as to how to compile a jar for 1.8

### ISSUE THREAD

**Issue by westover** [SanAndreasP/ClaySoldiersMod#126]
I am not a minecraft player but I am a software developer. The minecraft bug has caught my son like so many others. Could you perhaps give me a link to some resources or a guide I can use to compile a jar for 1.8.x

**Comment by SanAndreasP** [comment]
Well, there's currently no source of this mod available for MC 1.8, so you'd need to update it yourself.
To setup the workspace, read the "For Developers" part of the README.md

Please note that this mod uses the Manager Pack, so you need to either update that first or strip its usage out of the mod.

**Comment by SanAndreasP** [comment]
Since there's no response to this, I'll close it. If you have any questions regarding this topic, please open a new issue (and reference this one).
