### ISSUE TITLE
There Can Only Be One Clay Monarch

### ISSUE THREAD

**Issue by TheLaughingCow** [SanAndreasP/ClaySoldiersMod#128]
Soldiers will not pick up nuggets and become monarchs when there is already one currently in the arena, even if they are from different factions. (ie. If you give red a monarch, then yellow won't pick up a nugget unless you kill the red monarch.)

**Comment by SanAndreasP** [comment]
I will look into it.

**Comment by MBTshock** [comment]
With my experience you have to give them a nugget a little further away from thee first 1
