### ISSUE TITLE
My game doesnt load , HELP

### ISSUE THREAD

**Issue by Master323** [SanAndreasP/ClaySoldiersMod#133]
When i start minecraft , i am loging in and then when i click play nothing happens . Halp plz

**Comment by SanAndreasP** [comment]
Logs or it diidn't happen.
(<tt>.minecraft/logs/fml-client-latest.log</tt>, post it on https://gist.github.com and give us the link)

**Comment by SanAndreasP** [comment]
Since there's no response to this in over 2 weeks, I'll close this now. If you still have this problem, open up a new issue, and please provide logs next time.
