### ISSUE TITLE
villages

### ISSUE THREAD

**Issue by dude98** [SanAndreasP/ClaySoldiersMod#134]
could you make add to Their abilities to do things that would help they live life in a village?
i really like to make a village for them to live in but all they do is walk around so it gets kinda boring, it would be awesome if you did.

**Comment by Spartan322** [comment]
First, it was not making a village, they could just build a few structures, next, #17

**Comment by SanAndreasP** [comment]
They're soldiers, not villagers.

I'm playing with the thought of having villager features like farming, mining etc. (and the old building houses mechanic) existing as a seperate add-on to the mod. But that'll be a thought when the mod is out of beta.
