### ISSUE TITLE
How does the new nexus work?

### ISSUE THREAD

**Issue by dude98** [SanAndreasP/ClaySoldiersMod#135]
i want to use nexi/multiple nexus to make armories, could you help please?

**Comment by Spartan322** [comment]
That's not possible yet

**Comment by SanAndreasP** [comment]
Place nexus, right-click it with a soldier-doll of desire.
Repeat for other nexi.
Right-click nexi with gravel/snow/emerald to make them throw stuff at other enemies.
Sneak-right-click to heal nexi.
right-click with empty hand to (de-)activate nexi
Toggle with redstone signal (on or off) to toggle activation.

In the next update, there'll be a GUI to set the nexus properties in greater details (like the old ones did)

I'll keep this open until we've implemented the Nexus GUI

**Comment by Yoshiprime** [comment]
Wait the mod isnt dead? Not to be rude but I thought it died as there have been no new updates.

**Comment by Spartan322** [comment]
@Yoshiprime Be patient, don't hijack issues, it is very disrespectful and makes the issue comments very dirty, please refrain from doing that, also yes, also, unless this issue is being used to track the Nexus GUI, it probably better closed.

**Comment by Yoshiprime** [comment]
@Spartan322  Sorry about that I just thought the mod was kinda dead after the last overhaul as I haven't seen anyone talk about it for almost a year now, and I myself was wondering where the heck the Nexus GUI went.

**Comment by dude98** [comment]
Thank you and by the way, whenever i use the bowl, my game crashes

**Comment by SanAndreasP** [comment]
For why there isn't any updates recently: #136
For the bowl crash: Open up a new issue and provide the crash log.
