### ISSUE TITLE
New update info?

### ISSUE THREAD

**Issue by Alfykun55** [SanAndreasP/ClaySoldiersMod#136]
Hi, first of all, thank you for making such an amazing mod and woring hard on it :D im sure we all aprecciate your hard work and dedication.

So i was wondering when will the next update of your mod come out, and what will be added on it?

**Comment by Spartan322** [comment]
This question would probably be better stated on the forums, though you should know that (from my experience, both as one and knowing others and watching developments) developers usually hate being asked this for lots of reasons

**Comment by SanAndreasP** [comment]
I'm currently somewhat inactive because of time constrains IRL.
The mod will see an update when I get more spare time (probably around the holidays, but no promises, though)
