### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ACcrafter** [SanAndreasP/ClaySoldiersMod#137]
Hello this is a thing I've always wanted in clay soldiers i was wondering if you could add 3D vehicles and different types of them could hold different amounts and also add guns,.

**Comment by Spartan322** [comment]
The objective was for olden age weapons only, iirc, this was called out as something not to ask directly into the mod, though it could be set as an addon otherwise

**Comment by ACcrafter** [comment]
Are there addons? if so where can I get some?

**Comment by Spartan322** [comment]
No one has built any addons cause this mod is not complete enough to truly support a good API (from my experiences at least, also speculation)

**Comment by CliffracerX** [comment]
There are no addons, and I don't think the API has been finished yet.  We used to have a sort of half-functional one in 1.6, but that really only worked for adding new types of Clay Soldiers.

Also, as Spartan has said, making AI that can use vehicles and guns and whatnot in a useful way would be very difficult for this mod, as the Minecraft AI is pretty fiddly.

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
