### ISSUE TITLE
Gold "armour" on king?

### ISSUE THREAD

**Issue by Alejandroibo** [SanAndreasP/ClaySoldiersMod#140]
I was testing random stuff with the soldiers and then the white king grabbed a gold ingot and now he has some kind of golden armour, what is this? what does that? this wasn't writen in the minecraft mods page

I also saw a white soldier with his "easter egg" skin from past updates, but i never dropped a spawn egg in my arena.

Im going to do some test with the soldiers to know if theres something else that isn't mencioned on the page.

**Comment by Alejandroibo** [comment]
PD: i just spawn steve as a blu soldier without any item, so the "easter egg" thing is random

**Comment by Spartan322** [comment]
These are both planned behaviors, why do we have an issue tracking them? 
Gold Ingot Upgrade Ref: https://github.com/SanAndreasP/ClaySoldiersMod/blob/master/java/de/sanandrew/mods/claysoldiers/util/soldier/upgrade/misc/enchantment/UpgradeGoldIngot.java

The easter egg was found a while ago.

**Comment by SanAndreasP** [comment]
This is not an issue. We changed the golden crown to a golden "hoodie", because that won't interfere with the diamond crown of a supersoldier anymore.
https://github.com/SanAndreasP/ClaySoldiersMod/blob/master/java/de/sanandrew/mods/claysoldiers/client/event/SoldierModelRenderHandler.java#L61-L63
