### ISSUE TITLE
Glistering Melon

### ISSUE THREAD

**Issue by 0817Elaine** [SanAndreasP/ClaySoldiersMod#143]
I have an issue that a clay soldier with a glistering melon is healing himself when he's trying to heal other soldiers

**Comment by SanAndreasP** [comment]
That may probably be because I don't check if the "target" is the same as the healer himself and deny targeting.
I'll fix it.

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
