### ISSUE TITLE
Soldiers don't drop when killed, is this a bug or part of the mod

### ISSUE THREAD

**Issue by ispy92** [SanAndreasP/ClaySoldiersMod#144]
I was wondering why clay soldiers don't drop when I kill them. In older versions they would drop, so why don't they drop now? I have a few other mods installed, so it may just be mods clashing. But is this part of the game or not. Their items drop when killed but they do not.

**Comment by Spartan322** [comment]
Are they spawned from the Nexus?

**Comment by ispy92** [comment]
Nope. I started a survival world and I found a clay hut and I tried to kill and collect the soldiers inside, but they just droped, so I spawned the items of them in.

**Comment by Spartan322** [comment]
Pretty sure the clay versions spawn NBTs akin to the nexus

**Comment by SanAndreasP** [comment]
Yea, soldiers from the huts don't drop themselves. The only soldiers dropping themselves are the ones spawned from you while you're in survival mode.
