### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cjm4001** [SanAndreasP/ClaySoldiersMod#146]
Add clay huts again

**Comment by Spartan322** [comment]
They already explained why, #17, this is a duplicated

**Comment by dude98** [comment]
leave them alone about this cjm, they still have those things planned

**Comment by cjm4001** [comment]
Are you talking to a wall? That was posted three months ago punk kid.

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
