### ISSUE TITLE
When is the next update coming out?

### ISSUE THREAD

**Issue by cjm4001** [SanAndreasP/ClaySoldiersMod#147]
When is the next update coming?

**Comment by Spartan322** [comment]
this is a very rude question and honestly should not be asked on github

**Comment by westover** [comment]
... That isn't really that rude. But answering it that way is. Perhaps a simple "I don't know" would work. Just my 2 cents.

**Comment by cjm4001** [comment]
Not trying to be rude, but u are trolling alot of posts here. Just curious because I enjoy this mod alot.

**Comment by Spartan322** [comment]
Just telling you, when mod developers hear this (or any dev), they (or we) don't usually like that and it can be really annoying for us, also, the chance that you will ever get an answer (that isn't "we don't have one" or "I don't know") is slim to none, being patient works out better. Just play with the mod to your hearts content until they release it, cause that's probably the only real response that can be given for this question.

**Comment by cjm4001** [comment]
Makes sense.  I'll stick to reddit

**Comment by SanAndreasP** [comment]
yea, like others said, asking for an update is inappropriate, as usually the answer is: When it's done.
Most modders do it as a hobby, so they decide if and when mods get updated.

~~PS: cleaning out the issues now~~
