### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by AceShawt** [SanAndreasP/ClaySoldiersMod#148]
for some reason, i really dont know it wont load. I took everything out of the mods folder except the clay mods and i didnt put it there but a 1.8 folder but the folder is still in the mods folder of the .minecraft folder. i get an error message that says word for word "Forge Mod Loader has found a problem with your minecraft installation. The mods and versions listed below could not be found.

sapmanpack : minimum version required is 2.4.0

The file 'logs/fml-client-lates.log' contain more information"

i dont know if this is a problem with another thing such as another mod or its with the clay soldiers mod (which i REALLY want to play) so i was hoping that you could find what this error is about and if its about clay soldiers you can fix it. if not ill try to look into it. thanks 

oh and i would like to add that i just tried loading up the forge version without clay soldiers and it loaded up fine :/ maybe this helps

**Comment by Spartan322** [comment]
You need the SAPManager pack coremod, or else your minecraft will crash, this mod requires that mod. The instructions for installation clearly states this

**Comment by AceShawt** [comment]
i thought i installed that but i guess something went wrong while downloading. ill try and re-download it thanks

**Comment by ChilledSniper** [comment]
Im having the same problem, I have the manager pack but still wont load, what should I do?

**Comment by SanAndreasP** [comment]
How about you open up a new issue?
Provide the fml-client-latest.log via https://gist.github.com as a link.

I'm closing this, because of no response of OP in over 2 weeks
