### ISSUE TITLE
already zombified clay soldiers?

### ISSUE THREAD

**Issue by MBTshock** [SanAndreasP/ClaySoldiersMod#150]
When I do zombie battles I find it really frustrating when I have to put 1 guy down then give him an ender pearl then make him fight his teammate and yada yada yada. I was wondering if you could have like an already zombie clay soldier that you can put down. And also when like a red zombie clay soldier finds a blue zombie they attack each other...forever. One last thing I cant use the claycam when they r on a mount

**Comment by Spartan322** [comment]
Or you could just drop a stack of ender pearls and spawn a bunch (I think the nexus can be used too)

That first thing is not an issue (as far as I can tell)

Other thing is that second part is actually called hijacking an issue, two things about it, one, that should've been asked on the forums, and two, if it was a bug, should have been reported separately.

**Comment by SanAndreasP** [comment]
I'm planning a sort of "pre-configuration" module, where you can give the soldier items the upgrades and let them spawn with them.

~~PS: cleaning out the issues now~~

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
