### ISSUE TITLE
Allies?

### ISSUE THREAD

**Issue by iNCRYY** [SanAndreasP/ClaySoldiersMod#154]
Suggesting the ability to add allies for the soldiers? (ex. green and blue wont attack each other and attack others together)

Allies could open up more potential and more fun in battles.

**Comment by RenLie** [comment]
ya that's a good idea

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
