### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by snowclause123** [SanAndreasP/ClaySoldiersMod#155]
I downloaded mod. I know this mod but when I opening my world, game crashes!

**Comment by Spartan322** [comment]
Log (from Pastebin or Gist please, do not directly paste in)

**Comment by TheGamingToast** [comment]
Spartan322, I got the same problem, and I have a pastebin of it. http://pastebin.com/i2KaJA8D There yah go!

**Comment by SanAndreasP** [comment]
No log, no help.

~PS: cleaning out the issues now~
