### ISSUE TITLE
Basic issues

### ISSUE THREAD

**Issue by ShinyKekevoir** [SanAndreasP/ClaySoldiersMod#163]
I'll keep this simple

Soldiers can't pick up items from chests. I don't know why but they don't bother with them.

They don't build huts with stacks of wood.

They don't follow their dye or fishing rods. I don't know if this feature is taken out or not, but I remember older versions allowing me to guide my bois.

The nexus doesn't have a menu. Right clicking it makes it turn on. 

Basically, things i remember doing in older versions that i can't do anymore. Are some of these features taken out or is something wrong?

**Comment by Spartan322** [comment]
#17 Duplicate cause its been explained already

**Comment by SanAndreasP** [comment]
Yea, @Spartan322 already explained this is a dupe. Closing this.
