### ISSUE TITLE
Gunpowder/Magma cream and death drops.

### ISSUE THREAD

**Issue by maz09mohanad** [SanAndreasP/ClaySoldiersMod#164]
After a clay soldier with gunpowder or magma cream dies and explodes, the gunpowder/magma cream is dropped again and another soldier can pick it up.

Also, clay soldiers do not drop themselves on death if they are summoned in creative mode. I understand this is a feature, but it negates the use of clay to revive others during battles.

**Comment by SanAndreasP** [comment]
The first one is a bug indeed, will be fixed in the next version.
The second one will be reconsidered, I'd like to have it that you also consume the soldiers when used
(When starting the recode, I didn't know how to consume items on use in creative mode, so I stuck with it)

**Comment by maz09mohanad** [comment]
Also, noticed while playing that just about everything that can be picked up will drop on death, namely wheat, sugar, glass panes/bottles, sugarcanes.

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
