### ISSUE TITLE
Nexus

### ISSUE THREAD

**Issue by alarick23** [SanAndreasP/ClaySoldiersMod#166]
Please bring back the old nexus configurations on the new model . Like when you could go into the settings of the nexus tell it how much soldiers to spawn it would be nice just a opinion.

**Comment by Spartan322** [comment]
That name doesn't explain very well, could you make it more descriptive.

**Comment by alarick23** [comment]
The Clay Nexus you use it for never ending battles it's like a automatic clay soldier spawner.You use to can click on it and configurations would pop up but on the beta no configurations at all.Im pretty sure everyone wants more then like 10 soldiers spawning

**Comment by Spartan322** [comment]
I know what the Nexus is, but your title doesn't explain the purpose of the issue.

Also you might want to read #17 a bit

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
