### ISSUE TITLE
New idea you might like.

### ISSUE THREAD

**Issue by alarick23** [SanAndreasP/ClaySoldiersMod#167]
How about adding an new clay soldier mount a miniature ender dragon ,cake dragon , etc.

**Comment by eagle651** [comment]
adding more weapons and buffs will be good enough

**Comment by Spartan322** [comment]
Already discussed on the forum, and I was pretty sure they said absolutely not. Someone could however make an addon for it.

**Comment by SanAndreasP** [comment]
Yea, no dragons. We already have the pegasi and throwables to give to the soldiers.
