### ISSUE TITLE
Clay Soldiers Crashing - Minecraft 1.10.2 //  Forge1.10.2-12.18.2011 // Clay 1.7.10-2.0.0-beta 2 // ManPac

### ISSUE THREAD

**Issue by BlackKnight083** [SanAndreasP/ClaySoldiersMod#173]
I have downloaded and dragged the mods correctly, but Minecraft keeps crashing when trying to load the mods.

I have:
Minecraft 1.10.2
Forge 1.10-2-12.18.2011
Clay 1.7.10-2.0.0 beta 2
Manager Pack 1.7.10-2.5.1
Java 8 Update101

My latest crash report is attached to this pose.

[fml-client-latest.txt](https://github.com/SanAndreasP/ClaySoldiersMod/files/412268/fml-client-latest.txt)

Please let me know what is not correct.

**Comment by SanAndreasP** [comment]
Wrong Minecraft version. The mod is currently only for 1.7.10 (and below).
