### ISSUE TITLE
Clay Nexus Configuration

### ISSUE THREAD

**Issue by BDBubbles** [SanAndreasP/ClaySoldiersMod#174]
I've seen quite a few youtube videos of people using the old clay nexus design, and building these cool battle arenas, but with the new beta clay nexus in v.2.0.0, the nexus has NO configurations, and you cannot control how many soldiers spawn, and how often, or what items they spawn with, you can only control what color of soldier, and the nexus does not allow you to put mounts in it a spawn either. I would really like it if you could fix this in your next version.

**Comment by Spartan322** [comment]
#17 explains the problem.

**Comment by BDBubbles** [comment]
not really

**Comment by BDBubbles** [comment]
it's, just saying that there's more issues, and that you guys are going to fix them, "at some point"

**Comment by Spartan322** [comment]
https://github.com/SanAndreasP/ClaySoldiersMod/issues/17#issuecomment-63761364

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
