### ISSUE TITLE
Minecraft wont open

### ISSUE THREAD

**Issue by CrakinBonez** [SanAndreasP/ClaySoldiersMod#178]
whenever i put SAPManPack in my mods folder my minecraft wont open! but if i remove the SAPManPack it opens how can i fix this???

(sorry for my bad english)

**Comment by SanAndreasP** [comment]
https://github.com/SanAndreasP/ClaySoldiersMod/issues/177#issuecomment-247584218

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
