### ISSUE TITLE
Mini ballistas/little bows for archer soldiers

### ISSUE THREAD

**Issue by darthvader45** [SanAndreasP/ClaySoldiersMod#179]
maybe a stick+string+a mini plank could create a miniature ballista, which would fire arrows at other soldiers, while stick+string makes a mini bow for clay soldiers to pick up.  This could advance ranged warfare.

**Comment by SanAndreasP** [comment]
the current throwable items should give you the same capabillities.
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
