### ISSUE TITLE
Mod version update

### ISSUE THREAD

**Issue by P2KH** [SanAndreasP/ClaySoldiersMod#180]
I played this mod since minecraft version beta1.8. And I liked waiting this mod update its latest version. I love this mod because it was perfect mod for me. Anyway, I know you make this mod just hobby, so I don't want to tell you update this mod as soon as possibe. But I just wonder if you stop making this mod.(It NEVER means you update this mod ASAP!) I'm sorry that my english is hard to understand. But I will like this mod even you stop making this. Thank you for updating this mod since long time ago.

**Comment by SanAndreasP** [comment]
Here for info: https://player.me/feed/4766459
