### ISSUE TITLE
Ranged Attacks Instantly Kill Mounts

### ISSUE THREAD

**Issue by TorakWolf** [SanAndreasP/ClaySoldiersMod#181]
Just as the title says, and melee attacks don't have this bug.

Strangely enough, unmounted soldiers take ranged damage as usual.

**Comment by TorakWolf** [comment]
Any news?

**Comment by SanAndreasP** [comment]
It's a bug in the mount's attackEntityFrom method, which checks if the entity causing the damage is not fire and also is not a clay soldier. If that's true, it insta-kills it. What it needs to do is to check wether the entity itself or its "owner" (the throwing soldier) is not a soldier.
I would fix it in the next update, whenever I can get the time actually coding on the mod again :(

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
