### ISSUE TITLE
Clay soldiers tab does not show up in inventory

### ISSUE THREAD

**Issue by aoaguiar** [SanAndreasP/ClaySoldiersMod#183]
I have successfully created a new profile to use the old Minecraft version 1.7.10 and copied the mods file (both - clay soldiers and pack manager) into the "mods" folder under the new profile.
However, I can't find in the inventory or elsewhere how to use it.
Can you please help?

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
