### ISSUE TITLE
Instant Crash On Startup

### ISSUE THREAD

**Issue by Wh4tsMyName** [SanAndreasP/ClaySoldiersMod#188]
When I try to load the mod in Forge for 1.11.2, it crashes instantly. Thanks to the new Minecraft launcher layout, I can't provide crash details. It doesn't even show the Mojang screen. I've determined that the problem is the SAPManPack mod, but I apparently can't use the Clay Soldiers mod without it. (In case you're wondering, I have Java 7 Update 51 on a Windows 8.1 computer.) Any help?

**Comment by SanAndreasP** [comment]
The mod isn't for 1.11.2 out yet.
