### ISSUE TITLE
Clay Soldiers won't pick up anything

### ISSUE THREAD

**Issue by K1Fire12** [SanAndreasP/ClaySoldiersMod#190]
Put the answers below the following questions:
 -What version of Minecraft do you use?
1.10.2
 
 -What version of MinecraftForge do you use?
1.10.2

 -What version of SanLib do you use?
 1.10.2
 
 -What is the issue / bug you have encountered? Give us a short description.
No matter if it is sticks or emeralds, they just don't want to use/take any of the items I drop in their container.

 -How can it be reproduced?
I made a 5x5x2 obsidian container (no top so I could drop items in) and put one soldier in so I could make him a king (gold nugget). However, I soon realized that not only would he not pick up the gold nugget, he would not pick up anything else. I used sticks, leather, gunpowder, glowstone dust, slime balls, blaze rods, and so much more.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:

[latest.txt](https://github.com/SanAndreasP/ClaySoldiersMod/files/835940/latest.txt)

**Comment by SanAndreasP** [comment]
The upgrade system isn't released yet. It'll be in an upcoming version.
