### ISSUE TITLE
Crash Before Minecraft Opens

### ISSUE THREAD

**Issue by scriblemelego** [SanAndreasP/ClaySoldiersMod#191]
Whenever I try to launch Minecraft, the launcher (using technic launcher if that matters) closes for a bit, then reopens without MC launching.
I'm using Clay Soldiers 1.7.10 2.0.0 Beta 2 and SanAndreasP's Manager Pack 2.5.1 along with a number of other mods.

Here's the log: https://gist.github.com/scriblemelego/31bf1126fa023b5fb1c4b1300922f00e

Thanks in Advance!

**Comment by scriblemelego** [comment]
Just realized I have bookshelf installed, here's my log now that I uninstalled it:
https://gist.github.com/scriblemelego/6d0b2cace3f220ef7bd78202f5b2940b

**Comment by SanAndreasP** [comment]
Yea, 1.7.10 is not supported anymore. Sorry.
