### ISSUE TITLE
Clay Nexus Configuration

### ISSUE THREAD

**Issue by Dymetreus** [SanAndreasP/ClaySoldiersMod#195]
Put the answers below the following questions:
 -What version of Minecraft do you use?
 1.7.10
 
 -What version of MinecraftForge do you use?
10.13.4.1614

 -What version of SanLib do you use?
 2.5.1
 
 -What is the issue / bug you have encountered? Give us a short description.
I'm having issues regarding the clay nexus. I'm unaware as to how to access it's configuration. I right click it, and that simply turns it on and off, with the exception when I have a clay soldier in my hand, to which it simply then puts the soldier into the clay nexus.

**Comment by SanAndreasP** [comment]
The 1.7.10 version is incomplete, as in the nexus doesn't have a GUI.

Since the current actively developed alpha version is for 1.10.2 (which doesn't have a nexus yet), the 1.7.10 version won't change anymore.

**Comment by Dymetreus** [comment]
Do you know which version is the most complete one? I'd appreciate the answer.

**Comment by SanAndreasP** [comment]
The most complete one would be the v.9.1.1 for MC 1.5.1
