### ISSUE TITLE
I can't make my clay soldiers to pick wood

### ISSUE THREAD

**Issue by Rafa2601** [SanAndreasP/ClaySoldiersMod#196]
Make sure you check following things before you open a new issue:

[ ] Check that you use Java 8
[ ] Check that you use the latest MinecraftForge version available for your version of Minecraft
[ ] Check that you use the Minecraft version supported by the mod

Put the answers below the following questions:
 -What version of Minecraft do you use?
 
 
 -What version of MinecraftForge do you use?

 -What version of SanLib do you use?
 
 
 -What is the issue / bug you have encountered? Give us a short description.

 -How can it be reproduced?

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:

**Comment by CasperYT** [comment]
Close this because you didint fill in the form at all.

**Comment by SanAndreasP** [comment]
Not implemented in the current version, also this'll most likely end up as an addon anyway.
