### ISSUE TITLE
Just many problems....

### ISSUE THREAD

**Issue by CasperYT** [SanAndreasP/ClaySoldiersMod#197]
Make sure you check following things before you open a new issue:

[ya ] Check that you use Java 8
[ya ] Check that you use the latest MinecraftForge version available for your version of Minecraft
[ya ] Check that you use the Minecraft version supported by the mod

Put the answers below the following questions:
 -What version of Minecraft do you use?
1.7.10
 
 
 -What version of MinecraftForge do you use?
1.7.10

 -What version of SanLib do you use?
 cant find a version for 1.7.10
 
 -What is the issue / bug you have encountered? Give us a short description.
need bookshelf. downloaded and installed bookshelf crashes instantly.

 -How can it be reproduced?
idfk

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link: https://gist.github.com/anonymous/9ca110490b97be7750bb36b0ff11ab43

**Comment by SanAndreasP** [comment]
Manager Pack and Bookshelf are incompatible. 
Also 1.7.10 is not supported anymore (an alpha is out for 1.10.2), thus this won't be fixed.
