### ISSUE TITLE
Fatal Error after spawning a soldier @ MP /w MC 1.10.2 & Forge 12.18.3.2185

### ISSUE THREAD

**Issue by Accurexx** [SanAndreasP/ClaySoldiersMod#198]
Make sure you check following things before you open a new issue:

[X ] Check that you use Java 8
[X ] Check that you use the latest MinecraftForge version available for your version of Minecraft
[X ] Check that you use the Minecraft version supported by the mod

Put the answers below the following questions:
 -What version of Minecraft do you use?
 1.10.2
 
 -What version of MinecraftForge do you use?
forge-1.10.2-12.18.3.2185

 -What version of SanLib do you use?
 1.10.2-1.0.1
 
 -What is the issue / bug you have encountered? Give us a short description.
The mod works perfectly fine while spawning clay soldiers in the singeplayer. If I set up my Minecraft-Server with the Mod every player get next to a spawned clay soldier get disconnected because of an FatalError - no further clues why or crashreports :-/ The server it self is still running, but you have to rollback the world to a state before spawning, because the crashed players can't login.

 -How can it be reproduced?
I can reproduce this error while setting up a new minecraft forge server with the clay soldier mod and the sanlib and with my gamed.de-Server

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log)
Latest FML Server Log: https://gist.github.com/Accurexx/349510e3086d20b26cc26a1691bc26cc
Latest Server Log: https://gist.github.com/Accurexx/efccaa968c137badf8c9b50690363037

**Comment by SanAndreasP** [comment]
Can you give me the log from a client that is crashing? The server logs don't say anything except the disconnections happening.

**Comment by Accurexx** [comment]
Yes, of course. I though they might be useless, since the mod works fine in singleplayer, so it has to do something with the server :D

I hope this is the right file, at least the time matches.

https://gist.github.com/Accurexx/9346c76526b8d54f119fd3f6123c5d47

**Comment by SanAndreasP** [comment]
hm... could you try with just Clay Soldiers and SanLib installed and see if that works?

**Comment by Accurexx** [comment]
In about 3 hours. I'll give you an update as soon as  possible.

**Comment by Accurexx** [comment]
The FatalError still occurs. 

I've deleted all the mods from the server, except ClaySoldiersMod-1.10.2-3.0.0-alpha.1 and SanLib-1.10.2-1.0.1, same for the client.

FML Server log: https://gist.github.com/Accurexx/c5a32a6c1e839b8046c5769405f5871e
Client log: https://gist.github.com/Accurexx/eb447307efcb67cdb8b23a34c45f4983

**Comment by SanAndreasP** [comment]
I found the problem, I need to change the way my custom data serializer is initialized.

**Comment by Accurexx** [comment]
Ok, great. Were you able to reproduce the bug? If know, let me know if you need some tests.

**Comment by SanAndreasP** [comment]
I've released a new update. Please tell me if I indeed fixed this problem. Thanks :)

**Comment by Accurexx** [comment]
Seems to work right now. Thanks a lot!

**Comment by SanAndreasP** [comment]
yea, these errors are due to me not adding them properly to the registry, I'll have to fix that.
