### ISSUE TITLE
[Suggestion]  Player Controlled  ClaySoldier   

### ISSUE THREAD

**Issue by TripOptic** [SanAndreasP/ClaySoldiersMod#20]
This is a suggestion. Could you make a craftable Clay Soldier that players can control(Using special item) while looking through the ClayCam?

**Comment by SanAndreasP** [comment]
Theoretically it should be possible by now, but there are some things we need to consider when we're implementing it (how do you use redstone-dust, throw gravel, eat food etc.)

**Comment by CliffracerX** [comment]
It's been "possible" since 1.4, just really buggy.

I actually made a singleplayer-only at the time thing that let you control the Melonwool Soldiers from 1.4 Meloncraft, they were a tad buggy but you COULD still walk around and control one.

Will look into this at some point...

**Comment by CliffracerX** [comment]
So, while I've been updating my own mod Meloncraft, I found my old code that enabled the controllable soldiers.  Got it to the point of being able to see the world from the perspective of the Melonwool Soldier, which is a decent start.  Going to continue messing with the soldiers and see if I can get controls working.

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
