### ISSUE TITLE
Add back core upgrades

### ISSUE THREAD

**Issue by SanAndreasP** [SanAndreasP/ClaySoldiersMod#201]
- [x] **IronIngot**
`makes soldier vastly resistant to knockback, increases knockback dealt to others, both effects neutralized vs another iron ingot user`
- [x] **Brick**
`makes soldier extremely slow and less willing to move, will use ranged attacks if available before melee`
- [x] **String**
`makes soldier resist all damage from one explosion`
- [x] **Cactus**
`75% chance to negate burn time, halves total burn time otherwise`
- [x] **NetherBrick**
`gives burn time to any soldier that attacks nether brick user with unarmed attacks`

**Comment by Jountax** [comment]
Could have sworn the iron ingot also made soldiers unable to use mounts. Speaking of, I do hope you plan to add more than just the horses back. The lizards and turtles were awesome.
