### ISSUE TITLE
Add back behavior upgrades

### ISSUE THREAD

**Issue by SanAndreasP** [SanAndreasP/ClaySoldiersMod#202]
- [x] **Wheat**
`makes soldier never attack, even if hit first`
- [x] **Nether Wart**
`makes soldier attack its allies`
- [x] **Fermented Spider Eye**
`makes soldier not attack, unless attacked first`
- [x] **Rotten Flesh**
`makes soldier attack hostile mobs, if infected soldier will also attack friendly/passive mobs and players`
- [x] **Sponge**
`makes soldier not attack, not be attacked (except by zombie/netherwart soldiers), and use healing items on any soldier rather than just own team`

**Comment by Xerxeth** [comment]
What about the Ender Pearl?

> Ender pearl (Corrupts a clay soldier to attack others to corrupt them and will attack you, hard to kill with diamonds, best if you avoid giving super soldiers ender pearls)

From [Clay Soldiers Gamepedia](https://minecraft.gamepedia.com/Mods/Clay_Soldiers)

**Comment by SanAndreasP** [comment]
Ender pearls are listed here:
https://github.com/SanAndreasP/ClaySoldiersMod/issues/203

We moved some stuff around for the future.
Basically soldiers will only attack all other soldiers when infected with a pearl.
Rotten flesh makes them attack hostile mobs only when "normal" and also players / passive mobs when infected

**Comment by Xerxeth** [comment]
Ah there it is, must have skipped over it when I was looking at that list earlier, my bad!
