### ISSUE TITLE
Add back misc upgrades

### ISSUE THREAD

**Issue by SanAndreasP** [SanAndreasP/ClaySoldiersMod#203]
- [x] **Leather**
`20 use, reduces incoming physical damage by half (when used with bowl, only receives 25% of original damage),
incompatible with Rabbit Hide`
- [x] **Rabbit Hide**
`20 use, reduces incoming physical damage by 12.5%, grants half the speed boost of sugar,
incompatible with Leather`
- [x] **Food**
`4 use, heals soldier when below 25%;
food in a bowl (rabbit stew and mushroom stew, even modded soups) should drop bowls,
healed XP is hungerPoints * 0.5`
- [x] **GoldNugget**
`inf use, gives soldier a crown, all of team follows the king`
- [x] **Glowstone**
`inf use, makes soldier glow, block gives to infinite soldiers`
- [x] **Gunpowder**
`1 use, soldier explodes on death;
incompatible with magmacream/firework star`
- [x] **MagmaCream**
`1 use, places a 2 second time bomb on the soldier which deals the final attack if killed by melee hit,
incompatible with gunpowder/fireworkstar`
- [x] **Sugar**
`inf use, makes soldier move faster, incompatible with diamond`
- [x] **Clay**
`4 use, revives fallen soldiers of own color`
- [x] **GhastTear**
`2 use, revives brick dolls to own color`
- [x] **RedstoneDust**
`4 use, causes target to entirely stop attacking for 3 seconds, applied by all thrown and melee attacks,
Redstone Block as infinite redstone supply`
- [x] **Slimeball**
`5 use, causes target to entirely stop moving for 3 seconds, applied by all thrown and melee attacks,
Slimeblock as infinite slimeballs`
- [x] **Feather**
`inf use, soldier can not attack while falling, soldier's fall is slowed greatly and takes no damage on landing,
no effect with iron ingot or while mounted`
- [x] **GlassBottle/Pane/Block**
`inf use, doubles vision range, soldier can see stealthed enemies,
bottles and panes give 1, block as infinite supply,
stained glass gives colored goggles`
- [x] **Paper/Book**
`inf use, gives a plain cape, dyed paper and books give colored capes,
book as infinite supply`
- [x] **Diamond**
`inf use, gives super crown and cape, doubles number of uses for all limited use items, grants sugar speed boost, multiplies hp by 10,
incompatible with diamondblock`
- [x] **DiamondBlock**
`inf use, gives super crown and cape, multiplies limited use item uses by five, grants sugar speed boost, multiplies hp by 80,
incompatible with diamond`
- [x] **EnderPearl**
`inf use, soldier zombifies, gains +5 hp, heals fully when deals last hit to a target, targets slain become zombies,
dies after 10 minutes of no fighting`
- [x] **BlazePowder**
`1 use, instantly kills target with fire, turning it into brick doll`
- [x] **RedMushroom**
`1 use, applies poison to target`
- [x] **BrownMushroom**
`2 use, heals soldier for 10 hp when below 25%`
- [x] **LillyPad**
`inf use, soldier has pants and will float on water,
no effect when used with iron ingot`
- [x] **Egg**
`inf use, soldier is ghostly and can not be detected by enemies not wearing glass goggles, doubles damage output of shears,
will be detected when others wearing glasses`
- [x] **WheatSeed**
`inf use, soldier can NOT be infected by any zombification`
- [x] **WoodButton**
`inf use, increases melee damage by 1 when no weapon is equipped,
incompatible with stone button`
- [x] **StoneButton**
`inf use, increases melee damage by 2 when no weapon is equipped,
incompatible with wood button`
- [x] **MobHead**
`inf use, gives the soldier a mask to wear`
- [x] **FireworkStar**
`1 use, soldier explodes on death in a firework effect,
incompatible with gunpowder/magmacream`
- [x] **Rabbit Foot**
`inf use, jump boost allowing soldiers to climb 1.5 blocks, letting them get on top of fences and related structures`
- [x] **Prismarine Crystals**
`inf use, makes soldiers glitter, that's all`

**Comment by badtimetim** [comment]
you should bring back the ability for clay soldiers to make houses again it
sounds like a good idea why did you remove it

**Comment by SanAndreasP** [comment]
you've already asked that in another issue <.<
I've answered that there.
