### ISSUE TITLE
Mod not working, crashes the game.

### ISSUE THREAD

**Issue by SpaceBarTender** [SanAndreasP/ClaySoldiersMod#206]
Make sure you check following things before you open a new issue:

[ ] Check that you use Java 8
[ ] Check that you use the latest MinecraftForge version available for your version of Minecraft
[ ] Check that you use the Minecraft version supported by the mod

Put the answers below the following questions:
 -What version of Minecraft do you use?
 1.10.2
 
 -What version of MinecraftForge do you use?

1.10.2
 -What version of SanLib do you use?
 
 1.10.2-1.10.1
 -What is the issue / bug you have encountered? Give us a short description.

Error: java.lang.NoSuchMethodError: de.sanandrew.mods.claysoldiers.item.ItemSoldier.setCreativeTab(Lnet/minecraft/creativetab/CreativeTabs;)Lnet/minecraft/item/Item;

Showed me this error. The game would not run but would crash.
 -How can it be reproduced?
By starting the game.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link: 
[latest.png.zip](https://github.com/SanAndreasP/ClaySoldiersMod/files/1149351/latest.png.zip)

**Comment by SanAndreasP** [comment]
You're trying to use the -src JAR. Don't do that.
Remove the JAR files and redownload the mod (the correct jars should not include either -src nor -deobf in their filename).

**Comment by SanAndreasP** [comment]
I'm closing this due to no response. If you still have a problem, open up a new issue.
