### ISSUE TITLE
Soldiers will not pick up any modifiers 

### ISSUE THREAD

**Issue by cpaxson1** [SanAndreasP/ClaySoldiersMod#207]
Make sure you check following things before you open a new issue:

[ ] Check that you use Java 8
[ ] Check that you use the latest MinecraftForge version available for your version of Minecraft
[ ] Check that you use the Minecraft version supported by the mod

Put the answers below the following questions:
 -What version of Minecraft do you use?
 
 
 -What version of MinecraftForge do you use?

12.18.3.2185
 -What version of SanLib do you use?
 
 1.01
 -What is the issue / bug you have encountered? Give us a short description.

Soldiers will not pick up any modifiers.
 -How can it be reproduced?

Drop modifiers on soldiers and see that they do  not pick them up.
Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:

**Comment by SanAndreasP** [comment]
What version of Clay Soldiers do you use?

**Comment by cpaxson1** [comment]
1.10.2

The beta is not working for it..... but when I use the 1.7.10 version with
the Technic Launcher, it works perfectly.

**Comment by SanAndreasP** [comment]
that's the minecraft version...

Can you give me the logs?
>Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link

**Comment by cpaxson1** [comment]
Ok

**Comment by cpaxson1** [comment]
https://gist.github.com/cpaxson1/6d82e349ea355f40c49f2336f1904869

**Comment by SanAndreasP** [comment]
So in your log are 3 mistakes:
1. You use Minecraft 1.12. The latest mod version only supports 1.10.2 right now.
2. You don't have SanLib installed.
3. You use alpha 1, which doesn't have any soldier upgrades, thus they don't pick up anything. Alpha 2 is the latest release that includes upgrades.

You can get the latest Clay Soldiers Mod here:
https://minecraft.curseforge.com/projects/clay-soldiers-mod/files
You can get the latest SanLib here:
https://minecraft.curseforge.com/projects/sanlib/files

These are the official download links. Any other download locations/sites are neither endorsed nor checked by me.

**Comment by cpaxson1** [comment]
I downloaded SanLib and put it in the mods folder, and I was using a 1.10.2
forge profile, but I will re-install everything.  I play on 1.12 servers,
but play 1.10.2 mods.  Thanks!

**Comment by cpaxson1** [comment]
Also, how do you install SanLib?  I had the latest version in the mods
folder.  I don't know if that is correct.  Thanks!

**Comment by SanAndreasP** [comment]
just put the jar file in the mods folder, yes.
Make sure the jar file name does not contain either -src or -deobf with both SanLib and Clay Soldiers.

**Comment by cpaxson1** [comment]
Ok, then!
Thanks!
