### ISSUE TITLE
"missing "mod""

### ISSUE THREAD

**Issue by Coola101** [SanAndreasP/ClaySoldiersMod#208]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
Forge 1.10.2

What version of MinecraftForge do you use?
forge1.10.2-12.18.1.2043

What version of SanLib do you use?
Sanlib-1.10.2-1.0.1.jar

What version of Clay Soldiers do you use?
ClaySoldiersMod-1.10.2-3....ha.2.jar
 
What is the issue / bug you have encountered? Give us a short description
Whenever I launch Minecraft with all the settings listed above, It never goes to the title screen. Instead it gives me an error message saying that I don not have the mod: Forge 12.18.2.2099. I have know idea how to get said "mod".

How can it be reproduced?
Assumably launching with clay soldiers, and sanlib on forge1.10.2-12.18.1.2043

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
Could not attach: "We don't support that file type" (.log file)

**Comment by SanAndreasP** [comment]
well, if you take a look at your Forge version again, the error clearly states you have an older version installed. So update Forge.
