### ISSUE TITLE
Wood Won't Work

### ISSUE THREAD

**Issue by Zoxeh** [SanAndreasP/ClaySoldiersMod#209]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
Latest

What version of SanLib do you use?
Latest 

What version of Clay Soldiers do you use?
3.0.0
 
What is the issue / bug you have encountered? Give us a short description.
When I give 5 logs to the soldiers, and 20 if I made a king, they do not make a village. Done by chest too.

How can it be reproduced?
Drop 5 logs onto soldiers, and then crown king and give 20 logs and attempt with chest, nothing.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
No log file.

**Comment by SanAndreasP** [comment]
#196
