### ISSUE TITLE
Rabbit hides crash the game.

### ISSUE THREAD

**Issue by SaintSebastianMC** [SanAndreasP/ClaySoldiersMod#210]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.10/1.10.2

What version of MinecraftForge do you use?
1.10/1.10.2

What version of SanLib do you use?
1.10

What version of Clay Soldiers do you use?
1.10.2
 
What is the issue / bug you have encountered? Give us a short description.
whenever i drop rabbit hides to the soldiers the game crashes. every time i try to enter the world the soldiers pick up the rabbit hide in a second and i crash before i can do anything.

How can it be reproduced?
1. spawn in some soldiers
2. drop rabbit hides.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/SaintSebastianMC/e6763913897f55983690d7fa308baec7

**Comment by SanAndreasP** [comment]
the currently maintained version is for Minecraft 1.12. Please use that version before reporting bugs. If you still have this issue there, open up a new issue.

(or wait until I may do a backport to 1.10/1.11 as not much of importance has changed since then.)
