### ISSUE TITLE
Soldiers Drowning

### ISSUE THREAD

**Issue by KitaKiller** [SanAndreasP/ClaySoldiersMod#212]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[The latest forge]

What version of SanLib do you use?
[The latest SanLib]

What version of Clay Soldiers do you use?
[1.12 Alpha 4.1]
 
What is the issue / bug you have encountered? Give us a short description.
[when i give my soldiers lillypads they keep drowning]

How can it be reproduced?
[Give a soldier a lillypad and put him in Water]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[What?]

**Comment by tarper24** [comment]
Could not reproduce. Do your soldiers have an iron ingot upgrade? That makes them to heavy to float.
