### ISSUE TITLE
[Minecraft 1.12.2 Clay Soldiers 3.0.0-alpha.6] No recipe for any glass soldiers

### ISSUE THREAD

**Issue by VallenFrostweaver** [SanAndreasP/ClaySoldiersMod#215]
Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[14.23.1.2601]

What version of SanLib do you use?
[1.3.1]

What version of Clay Soldiers do you use?
[3.0.0-alpha.6]
 
What is the issue / bug you have encountered? Give us a short description.
[No recipe and can't craft any color glass soldiers]

How can it be reproduced?
[Try crafting a glass soldier]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[N/A]

**Comment by SanAndreasP** [comment]
Forgot to add recipes for those, whoops.
Will be fixed in alpha 7

**Comment by SanAndreasP** [comment]
I've released alpha 7 containing the recipes now. It also fixes the language files, since they weren't loaded properly and resulted in an untranslated mod: https://minecraft.curseforge.com/projects/clay-soldiers-mod/files/2523738
