### ISSUE TITLE
Explain?!

### ISSUE THREAD

**Issue by SpectralKyurem** [SanAndreasP/ClaySoldiersMod#217]
![2018-02-25_19 21 05](https://user-images.githubusercontent.com/36824834/36648419-61d2fb92-1a61-11e8-9cf0-7d4c12053966.png)

So I was messing around with soldiers, and this thing spawned (I naturally gave it items for sake of screenshot). But what is this? Also if you want to dupe it spawn regular yellow soldiers until it spawns.

![2018-02-25_19 26 09](https://user-images.githubusercontent.com/36824834/36648446-c7ed8776-1a61-11e8-8677-b7f94151db9e.png)
(Front view)

**Comment by SanAndreasP** [comment]
It's an easter egg, a rare skin.

Every team has one or more rare skins, some have one or more unique ones as well.


Also these will be accessible via another method in the future.

**Comment by SpectralKyurem** [comment]
I see, thank you for responding, I did not know there were easter egg skins
