### ISSUE TITLE
[1.12.2] Crash when looking at clay soldier

### ISSUE THREAD

**Issue by QAngelusQ** [SanAndreasP/ClaySoldiersMod#218]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[Minecraft 1.12.2]

What version of MinecraftForge do you use?
[forge-1.12.2-14.23.2.2611]

What version of SanLib do you use?
[SanLib-1.12-1.3.1]

What version of Clay Soldiers do you use?
[ClaySoldiersMod-1.12-3.0.0-alpha.9]
 
What is the issue / bug you have encountered? Give us a short description.
[When attempting to look at the green clay soldier with WAILA mods installed, client crashes]

How can it be reproduced?
[Spawn a Green Clay Soldier. Attempt to look at it, and it will crash]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[Latest: https://gist.github.com/QAngelusQ/312f5ca99f3e782097b4ba893c54f0c4
Crash Report: https://gist.github.com/QAngelusQ/384ba7a16f92fb2037abc88e4a4aaa7b ]

**Comment by SanAndreasP** [comment]
ClaySoldiers 3.0.0-alpha.9.1 fixes the issue. You can download it from CurseForge once they approve the files.
