### ISSUE TITLE
server hang

### ISSUE THREAD

**Issue by MrSkittlesROTR** [SanAndreasP/ClaySoldiersMod#220]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[1.12.2-14.23.2.2613]

What version of SanLib do you use?
[SanLib-1.12-1.3.1]

What version of Clay Soldiers do you use?
[Clay Soldiers 1.12.2-3.0.0-alpha9.1]
 
What is the issue / bug you have encountered? Give us a short description.
server hang with player kicks on spawning soldiers
works fine in singleplayer

How can it be reproduced?
[try to spawn in/place anything from the mod]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[Link to log file]

Log files showed nothing on the error just that players were disconnected.

**Comment by SanAndreasP** [comment]
I cannot reproduce it. Can you give me the log files from the server and a player that was kicked from it (even if you think there's nothing in there)?

**Comment by MrSkittlesROTR** [comment]
https://gist.github.com/MrSkittlesROTR/9f96fb3ea24fa5aa4554ed9e5572bfc3
on placing a clay soldier it just instantly disconnects all players on, cant rejoin the server until its restarted and the mod is taken out.
No disconnect reason logged in the server logs and our player data is saved threw nucleus which just stores the uuid, name, logoff cords and effects on player at the time.

**Comment by SanAndreasP** [comment]
Taht's a Sponge server. I suspect that they do _something_ differently than a vanilla Forge server causing issues, since I cannot reproduce it on my own and the log you gave me doesn't indicate on any wrongdoing on my part.

I suggest bringing that issue to the Sponge devs, they probably have more of a clue what's wrong than I do: https://github.com/SpongePowered/SpongeForge/issues

**Comment by MrSkittlesROTR** [comment]
ok i will do, thank you.
