### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#221]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2
What version of MinecraftForge do you use?
1.12.2 - 14.23.2.2635
What version of SanLib do you use?
SanLib-1.12-1.3.1
What version of Clay Soldiers do you use?
ClaySoldiersMod-1.12.2-3.0.0-alpha.9.1
 
What is the issue / bug you have encountered? Give us a short description.
On my server with quark mod and clay soldiers installed, it all of a sudden crashed at random times. And when I try to reboot server, it crashes again.

How can it be reproduced?
Not sure.
[crash-2018-03-26_18.35.41-server.txt](https://github.com/SanAndreasP/ClaySoldiersMod/files/1849875/crash-2018-03-26_18.35.41-server.txt)

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[Link to log file]

**Comment by SanAndreasP** [comment]
Try without quark and see if it happens again.
It seems like something is messing with particles...

**Comment by BobRossss** [comment]
Ok I will try. Thanks for quick response.

**Comment by BobRossss** [comment]
Works on single player world.

**Comment by BobRossss** [comment]
Wait, old version of world.

**Comment by BobRossss** [comment]
Ok yes, it works.

**Comment by BobRossss** [comment]
Yeah I think something happened with quark, I backuped the server and it works.

**Comment by BobRossss** [comment]
Thanks.

**Comment by SanAndreasP** [comment]
You should open an issue on Quarks' repo then: https://github.com/Vazkii/Quark/issues
