### ISSUE TITLE
Server crashes without quark

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#222]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
1.12.2 14.23.2.2635, server is universal version

What version of SanLib do you use?
SanLib-1.12-1.3.1

What version of Clay Soldiers do you use?
 ClaySoldiersMod-1.12.2-3.0.0-alpha.9.1
 
What is the issue / bug you have encountered? Give us a short description.
Server crashes when playing on clay soldiers sometimes.
How can it be reproduced?
I gave a powder block to a diamond cape soldier and went into a cave and placed torches, but I backuped the server and still does it so I'm not sure.
[crash-2018-03-28_08.17.03-server.txt](https://github.com/SanAndreasP/ClaySoldiersMod/files/1856121/crash-2018-03-28_08.17.03-server.txt)

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/BobRossss/f959a4df0ee9001b9d3a738034235fbc

**Comment by SanAndreasP** [comment]
uh... so your java apparently doesn't define Arrays.asList as usual and doesn't return a modifiable list...
I'll fix it in the next version.

**Comment by BobRossss** [comment]
Thanks for quick response! Happy that this is gonna be fixed.

**Comment by SanAndreasP** [comment]
Forgot to mention, this bug has been fixed in the commit bcbb56b962bb4404a33c9d9f58e250f4c2cc8345
It will be public once the Clay Lexicon has been finished.
