### ISSUE TITLE
Wool and goggles

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#223]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
1.12.2 14.23.2.2635, server is universal version

What version of SanLib do you use?
SanLib-1.12-1.3.1

What version of Clay Soldiers do you use?
ClaySoldiersMod-1.12.2-3.0.0-alpha.9.1

What is the issue / bug you have encountered? Give us a short description.
When soldier has goggles on it appears that the wool turns yellow.
How can it be reproduced?
Give a soldier leather with a colored wool such as green and goggles.
![2018-03-28_16 49 47](https://user-images.githubusercontent.com/37054224/38058410-59901e42-32a8-11e8-9580-38b5b3442e26.png)

**Comment by SanAndreasP** [comment]
I see what happens after testing... the goggles leak a GL state, thus making the wool "glow" in weird colors.

will be fixed in the next version

**Comment by BobRossss** [comment]
Thanks for responding fast.

**Comment by SanAndreasP** [comment]
Forgot to mention, this bug has been fixed in the commit bcbb56b
It will be public once the Clay Lexicon has been finished.
