### ISSUE TITLE
Shield too far out (Bug?)

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#224]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
1.12.2 14.23.2.2635, server is universal version

What version of SanLib do you use?
SanLib-1.12-1.3.1

What version of Clay Soldiers do you use?
ClaySoldiersMod-1.12.2-3.0.0-alpha.9.1

What is the issue / bug you have encountered? Give us a short description.
The soldier's shield looks too far out.
How can it be reproduced?
Give a soldier a bowl and you will see that it is not connected to his hand.
![2018-03-29_11 09 18](https://user-images.githubusercontent.com/37054224/38100105-0fdc0f1e-3342-11e8-84ff-c10e2e50fd41.png)

**Comment by SanAndreasP** [comment]
I'll make them stick out their hands more.
The reason the shield is so far out is because it'll noticeably clip through their bodies when moving.

**Comment by SanAndreasP** [comment]
sorry, wrong issue closed in that commit
