### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#225]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.2.26.40

What version of SanLib do you use?
1.4.2

What version of Clay Soldiers do you use?
Alpha 9,1
 
What is the issue / bug you have encountered? Give us a short description.
This time when I log in into the server, it crashes the server every time.
EDIT: I have not been able to come on since this started happening.

How can it be reproduced?
Not sure
[crash-2018-02-04_08.53.22-server.txt](https://github.com/SanAndreasP/ClaySoldiersMod/files/1886859/crash-2018-02-04_08.53.22-server.txt)

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/BobRossss/03833333a56323932d31773a9eb9c91a

**Comment by SanAndreasP** [comment]
Not a mod issue, seems you don't have the right file permissions on your session.lock file of your server world. For more info, look here: https://gaming.stackexchange.com/questions/184226/how-do-i-fix-the-failed-to-check-session-lock-for-world-error

**Comment by BobRossss** [comment]
Oh, ok thanks! Sorry for wasting your time.
