### ISSUE TITLE
clay soldiers without the punch animation and floating when hurt... and some ideas.

### ISSUE THREAD

**Issue by jesus11q** [SanAndreasP/ClaySoldiersMod#226]
hi guys. i have this bug.

Do you use Java 8?
yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
[Forge Version Number]

What version of SanLib do you use?
1.12.2-1.4.2

What version of Clay Soldiers do you use?
1.12.2-3.0.0-alpha.9.1
 
What is the issue / bug you have encountered? Give us a short description.
when i start a battle the soldiers dont have the punch animation like the old mod, and when one soldier its hurted, float a little bit.

How can it be reproduced?
1- start a battle and begin.

2- watch the soldiers.

3-and the soldiers battle animation its diferent and strange because the float efect and no-hurt animation.

here is a screenshot:
![2018-04-27_16 24 47](https://user-images.githubusercontent.com/38771931/39383031-b5786bac-4a35-11e8-960c-047c27d38d6f.png)

the battles of the soldiers are very strange with that floating efect and without the punch animation... please fix it in the next update.

oh and... im gonna give some ideas for the next update:

-sponge soldiers.

-apple soldiers.

-mecha soldiers (a robot soldier)

-magma soldiers.

-bedrock soldiers (make them the only soldier pacific type).

-bring to light: the star fruit.

-cobblestone soldiers.

-wool soldiers. i know that its disapproved, but use the classic wool textures for make them more distinguashable.

-end-items. why that are disapproved? that maybe will be cool!

-disapproved mounts. why? dragons are very cool!

-bring back this: when the soldiers attacks the hostile mobs like in the classic mod.

-why no-man-made objects? thats maybe will be cool.

-bring to light: dog and cat mounts.

-cactus soldiers

-clay skeleton.

-cake soldiers.

-cookie soldiers.

-Golden apple soldiers( a counterpart of the normal apple soldiers)

-clay creeper.

-clay snowman.

-clay enderman.

-players tools and weapons: make them little like the soldiers weapons

-boats, chariots, carts: make the little too.

-concrete soldiers: make them with only one simple color for one like the concrete blocks. with the simple color will be distinguashable

-add some villages like the normal MC villages.

-add some monumetal structures.

-if you can, add a alien soldiers and space oxygen helmet addon for the galacticraft mod.

thanks

**Comment by SanAndreasP** [comment]
1. Suggestions go here: https://github.com/SanAndreasP/ClaySoldiersMod/issues/205 Please read the first post carefully, as it contains all suggestions that are already planned/rejected/done.
2. The arm swing is a visual bug indeed, I'll fix it in the upcoming release
3. The floating thing: Please make a new issue for that. It gets very confusing to have multiple issues in one thread. Also please provide a video (or screenshots) as I don't see what you meant by that.

**Comment by SanAndreasP** [comment]
closed this in a223d98
