### ISSUE TITLE
jump-floating effect when a soldier its hurted.

### ISSUE THREAD

**Issue by jesus11q** [SanAndreasP/ClaySoldiersMod#227]
here is another bug. originally it was mentioned in the first bug issue but the author of the mod asked me to publish it in another issue, and here it is: 

Do you use Java 8?
yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
the lastest version

What version of SanLib do you use?
1.12.2-1.4.2

What version of Clay Soldiers do you use?
1.12.2-3.0.0-alpha.9.1

What is the issue / bug you have encountered? Give us a short description.
when i start a battle, when a soldier its hurted, float a little bit.

How can it be reproduced?
1- start a battle and begin.

2- watch the soldiers.

3-and the soldiers battle animation its diferent and strange because the float efect animation.

here is a screenshot:

![2018-04-27_16 24 47](https://user-images.githubusercontent.com/38771931/39444537-231f65e6-4c86-11e8-9e0d-67588b8f7882.png)

when a soldier its hurted by another, presents a floating jump efect and back to the floor, maybe this hurt-jump its a bug because in the 1.7.10 version that bug don't exist, and besides in the 1.5.2 version the jump its different and better: the jump its a little hurt-jump, but in this version the hurt-jump its more slower and ugly, and when that happens, the soldier fall to the floor but slower and with a strange following effect...

steps to see this bug:

1- start a battle with 1 soldier vs 1 soldier

2- look at the soldiers

3 and when 1 of the 2 soldiers its hurted, jump, but with a slow and strange jump.

i hope if this get fixed in the next update please, i want to see that hurt-jump like in the 1.7.10.

ideas note: i put my mod ideas in the suggestions tread, see it

**Comment by jesus11q** [comment]
why i don't got any comment or something of this? SanandreasP are you busy or what?

**Comment by SanAndreasP** [comment]
yes, I am busy, there's no need to be so grumpy about it (a simple "bump" would've been enough).

This could be because Minecrafts backend changed from 1.7.10 to 1.8 (the singleplayer is now just "local multiplayer", the client connecting to an integrated server instance), thus depending on your PCd performance, position and motion can get a bit slowed down (this also happens with vanilla mobs/animals, just to a lesser extend).

A video showing your issue would be nice, to confirm if that's a performance problem.

**Comment by SanAndreasP** [comment]
given that there's no answer to this, I'm going to close this issue. If you still have this issue, please open up a new issue, including a video showing the problem.
