### ISSUE TITLE
Caught exception from Clay Soldiers Mod

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#229]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.3.2666

What version of SanLib do you use?
1.4.4

What version of Clay Soldiers do you use?
Beta 1
 
What is the issue / bug you have encountered? Give us a short description.
Game crashes when I load it up with Connected Textures Mod, Chisel, Quark, Autoreglib, and Sanlib

How can it be reproduced?
Put all the the mods I just mentioned in and try to load the game up. (Not sure if it is those mods though)

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[crash-2018-07-15_20.17.55-client.txt](https://github.com/SanAndreasP/ClaySoldiersMod/files/2196381/crash-2018-07-15_20.17.55-client.txt)

**Comment by SanAndreasP** [comment]
There'll be a beta 1.1 out soon. Please test it out and if it persists, reply to this issue with new logs and I'll re-open it

**Comment by BobRossss** [comment]
Alright. Thanks!
