### ISSUE TITLE
Clay Soldiers Wont Load

### ISSUE THREAD

**Issue by SlayerSlapper** [SanAndreasP/ClaySoldiersMod#23]
I have your Manager Pack installed but it doesn't recognize it.

Here are the logs: 
 The Logs wont show up

**Comment by SlayerSlapper** [comment]
Logs wont Show up

**Comment by SanAndreasP** [comment]
logs are in .minecraft/logs/fml-client-latest.log. Please use gist.github.com to post it and provide the link here.

**Comment by SlayerSlapper** [comment]
https://gist.github.com/SlayerSlapper/e918d5d94a6f15fc35d6
Here ya go. Please hurry i really want to play with your mod!!!!

**Comment by SanAndreasP** [comment]
[12:08:45] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.10.2, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home 

Update your Java: http://www.minecraftforum.net/forums/minecraft-discussion/discussion/2247090-tutorial-how-to-use-java-7-on-mac
Or get the new launcher from Mojang which automatically ships Java 8.

**Comment by SanAndreasP** [comment]
Referencing #67
