### ISSUE TITLE
Can't get clay nexus. How?

### ISSUE THREAD

**Issue by SanderMC24** [SanAndreasP/ClaySoldiersMod#231]
Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[14.23.2.2631]

What version of SanLib do you use?
[1.4.2]

What version of Clay Soldiers do you use?
[3.0.0-alpha.9.1]
 

i can't get clay nexus and clay statitics display, is this normal? Is this typical to my version?

Can you please do something about this? Its very weard

**Comment by SanAndreasP** [comment]
not implemented yet
