### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by sajmonkox** [SanAndreasP/ClaySoldiersMod#232]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes/No]

What version of Minecraft do you use?
[Minecraft Version Number]

What version of MinecraftForge do you use?
[Forge Version Number]

What version of SanLib do you use?
[SanLib Version Number]

What version of Clay Soldiers do you use?
[Clay Soldiers Version Number]
 
What is the issue / bug you have encountered? Give us a short description.
[Description]

How can it be reproduced?
[Steps]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[Link to log file]

**Comment by sajmonkox** [comment]
hi guys

**Comment by SanAndreasP** [comment]
This is not an issue.... if you want to discuss stuff, you can go to our discord here: https://t.co/ydAZKc0Kyt
Posting here is for issues and suggestions only.
