### ISSUE TITLE
Crash!!!

### ISSUE THREAD

**Issue by G0LD3NC0L4** [SanAndreasP/ClaySoldiersMod#236]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[14.23]

What version of SanLib do you use?
[1.4.2.4.2708]

What version of Clay Soldiers do you use?
[beta.1.1]
 
What is the issue / bug you have encountered? Give us a short description.
[When interacting with the Clay Lexicon, certain options produce a forced log out, e.i. a crash]

How can it be reproduced?
[Open the Clay Lexicon, select mounts, then select horses. Several other options also produce the same effect. Such as the disruptor inside the Miscellaneous section.]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[https://gist.github.com/G0LD3NC0L4/85db9838407bf13f27d4ebac99475708]

**Comment by SanAndreasP** [comment]
Update SanLib
