### ISSUE TITLE
Soldiers suffocate in corners with no corners

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#237]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.4.2757

What version of SanLib do you use?
1.5.0

What version of Clay Soldiers do you use?
Beta 1.1
 
What is the issue / bug you have encountered? Give us a short description.
Soldiers die in corners that have no corners.

How can it be reproduced?
Make walls connecting but with no corners.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[Link to log file]

**Comment by SanAndreasP** [comment]
See if this is still an issue with the new update

**Comment by BobRossss** [comment]
It's not.

**Comment by SanAndreasP** [comment]
Cool, closing this, then :+1:

**Comment by Potshott** [comment]
lol
