### ISSUE TITLE
Geko Bug 

### ISSUE THREAD

**Issue by Potshott** [SanAndreasP/ClaySoldiersMod#238]
When a clay soldier is riding a geko and the geko spins on a stair while jumping with a block over it the clay soldier takes damage

**Comment by Potshott** [comment]
Also clay soldiers who are riding rabbit barely move

**Comment by SanAndreasP** [comment]
I consider this a duplicate of #241 (even if this issue is technically younger)

**Comment by Potshott** [comment]
ok
