### ISSUE TITLE
sapmanpack could not be found.

### ISSUE THREAD

**Issue by 4everLink** [SanAndreasP/ClaySoldiersMod#24]
so I've tried running Minecraft version 1.7.10, forge version 10.13.2.1291. I've tried doing so with JUST claysolders and the sapmanpack in my magiclauners mods list. I've tried it with sampan on top and on the bottom, and it doesn't seem to matter what I try, I get the same result. Minecraft successfully opens, but instead of going to the menu screen I get this msg:
Forge Mod Loader has found a problem with your Minecraft installation.
the mods and versions listed below could not be found:
sapmanpack: minimum version required is 2.4.0 (which I have)

here is the log from my most reacent attempt.:

https://gist.github.com/4everLink/64fc5f2cbe1b8c53f043

**Comment by SanAndreasP** [comment]
Why are the mods inside a folder called "old-mods"? Mods usually go into the "mods" folder.

**Comment by 4everLink** [comment]
because then forge tries to load up any mods in that folder, even tho I have them all in sub folders like 1.2.5, 1.4, 1.6, ect. so I made an old-mods folder that I could put in the magic launcher.
it seemed to fix some issue I had in the past that I can't remember now.

**Comment by SanAndreasP** [comment]
This shouldn't happen. But anyway, have you tried using different profiles? Other than that, it's not an issue with the mod, so I'll close this for now.

**Comment by 4everLink** [comment]
oh now I remember >.> when I change it back to "mods" folder, magiclauncher automatically loads them all as external mods. but yes I' messing around with the profile, tho I'm not sure what it's gunna change. and with the mods folder and such.

**Comment by 4everLink** [comment]
seem magic launcher can find it now. but the all mods are now automatically external thing is kinda annoying. anyways I can play with my clay again, so let the wars commence!
