### ISSUE TITLE
Soldiers drowning with lilypads

### ISSUE THREAD

**Issue by ACcrafter** [SanAndreasP/ClaySoldiersMod#242]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes
What version of Minecraft do you use?
1.7.10

What version of MinecraftForge do you use?
1.7.10
What version of SanLib do you use?
1.7.10

What version of Clay Soldiers do you use?
1.7.10
 
What is the issue / bug you have encountered? Give us a short description.
Soldiers drowning with lilypads

How can it be reproduced?
Give soldiers lilypads then have them go in the water

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
Didn't crash

**Comment by SanAndreasP** [comment]
1.7.10 is not supported anymore
