### ISSUE TITLE
lily pad bug

### ISSUE THREAD

**Issue by Potshott** [SanAndreasP/ClaySoldiersMod#243]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.4.2757

What version of SanLib do you use?
1.5.0

What version of Clay Soldiers do you use?
1.12.2 beta
What is the issue / bug you have encountered? Give us a short description.
if you make a one and a half block deep pool the clay soldiers with lily pad and without will sink to the bottom but not drown because half block cancel out water

How can it be reproduced?
make a one and a half block deep pool give a clay soldiers alily pad and put the clay soldiers in it

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[Link to log file]
![2018-10-21_15 20 10](https://user-images.githubusercontent.com/44125490/47268181-7f4ccf00-d545-11e8-9099-13b038d917fd.png)
but not as deep as this

**Comment by SanAndreasP** [comment]
Half blocks do not count as water, so they don't try to swim in it. This is an issue on how Minecraft itself works, nothing we can do about.

You can revisit this once Forge 1.13 drops (and this mod gets updated) and see if it'll still happen with the new water mechanics.

**Comment by Potshott** [comment]
ok ty
