### ISSUE TITLE
Game Crashes Upon Loading

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#246]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?

14.23.4.757
What version of SanLib do you use?
1.5.0

What version of Clay Soldiers do you use?
Beta 2
 
What is the issue / bug you have encountered? Give us a short description.
It worked before, now it doesn't.

How can it be reproduced?
Try to load minecraft with the mod.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/BobRossss/9569b5507cbd4522e5d3e4618e248f42

**Comment by SanAndreasP** [comment]
please post the latest.log:
```java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!```

**Comment by SanAndreasP** [comment]
Nevermind, gradle f-ed up and included deleted / moved classes in the package. I'll reupload the cleansed release ASAP

**Comment by SanAndreasP** [comment]
https://minecraft.curseforge.com/projects/clay-soldiers-mod/files/2653725
