### ISSUE TITLE
Clay Lexicon doesn't show text when clicking on upgrade.

### ISSUE THREAD

**Issue by BobRossss** [SanAndreasP/ClaySoldiersMod#247]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?

14.23.4.757
What version of SanLib do you use?
1.5.0

What version of Clay Soldiers do you use?
Beta 2

What is the issue / bug you have encountered? Give us a short description.
Clay Lexicon shows no text when clicking on the upgrades.

How can it be reproduced?
Open the Clay Lexicon.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[2018-12-29-6.log.gz](https://github.com/SanAndreasP/ClaySoldiersMod/files/2716839/2018-12-29-6.log.gz)
![2018-12-29_19 26 15](https://user-images.githubusercontent.com/37054224/50543513-f931b200-0b9f-11e9-8d49-11d8bb743aff.png)

**Comment by SanAndreasP** [comment]
Get the new SanLib update, it fixes that:
https://minecraft.curseforge.com/projects/sanlib/files/2653971
