### ISSUE TITLE
Clay Nexus Interface??

### ISSUE THREAD

**Issue by Shakeem84** [SanAndreasP/ClaySoldiersMod#25]
The clay nexus doesn't seem to have a GUI or interface and I am not sure if it has one or not. I have tried to open one, but it failed. All I can currently do is manually place a soldier in by right-clicking it into the nexus and add a thrown item to it. Is this a bug or intentional? Will there be a tool to open a clay nexus GUI such as the clay stats item in the future?

**Comment by SanAndreasP** [comment]
The nexus is still WIP, so no GUI yet.

**Comment by Shakeem84** [comment]
Thanks! I got a bit worried, but now I see. I can't wait until it's finished!
