### ISSUE TITLE
"Suggestion" tameable clay companions?

### ISSUE THREAD

**Issue by ClayNingyo** [SanAndreasP/ClaySoldiersMod#30]
I made this comment back in 1.2.3, but you might not have seen it, so here goes:
do you think you can add neutral coloured clay animals that can't be ridden, but can instead be tamed to fight alongside a colour of clay soldier? I was thinking of something like a clay wolf, that when tamed, will have a collar around it, change into the colour of its tamer, and then fight alongside it. what do you think?

**Comment by SanAndreasP** [comment]
It is planned.

**Comment by SanAndreasP** [comment]
reopened, because milestone

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
