### ISSUE TITLE
routes

### ISSUE THREAD

**Issue by po123po** [SanAndreasP/ClaySoldiersMod#31]
This is a suggestion.
do you think that u guys can make routes for clay soldiers?
it is like this:
decided by players,
can be for one or the clay soldiers with same color,
when they sees enemys on their routes,they attack them

Thanks

**Comment by CliffracerX** [comment]
I may be able to work on this at some point, as I already have some experience in making RTS-Style movement for mobs.

**Comment by po123po** [comment]
thx

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
