### ISSUE TITLE
Suggestion: Clay Companions for clay soldiers

### ISSUE THREAD

**Issue by ClayNingyo** [SanAndreasP/ClaySoldiersMod#34]
Kind of hard to explain, so I'll just make an example:
For example, you can spawn a clay wolf with a neutral colour, and it just wanders around. 
A clay soldier can use food given to it to tame the wolf, thus changing the wolf's pelt colour to the clay soldier who tamed it. A wolf can't equip items, can't be ridden on, but will follow the clay soldier who tamed it, and fights alongside its clay owner until its final breath. Something like a tameable battle pet for clay soldiers.

**Comment by SanAndreasP** [comment]
Didn't you already suggest this here #30 ?

**Comment by ClayNingyo** [comment]
sorry, didn't see it loaded at one point, so I though I must have forgotten to upload it XP
