### ISSUE TITLE
Option set clay soliders hostile to hostile mobs (or any mob who I attack/attacks me)

### ISSUE THREAD

**Issue by GotchaGimmeThanks** [SanAndreasP/ClaySoldiersMod#38]
I have fun making factories and such in minecraft, and I've always thought the coolest thing would be if it was all to arm a war effort. This mod is ALMOST exactly what I've always wanted. But it seems like I'm limited to "playing chess against myself" or playing competitively against others.

I would love to be able to (perhaps cooperatively) take on the vanilla boss fights, and possibly some other mod challenges, while setting a rule for myself. I don't attack with advanced gear, it's up to my clay army that I've put great effort into producing and arming.

I've even heard that some older version had this option? Any information would be greatly appreciated, thank you.

**Comment by Spartan322** [comment]
I'm pretty sure this request is the same as #30 .

**Comment by GotchaGimmeThanks** [comment]
No, he seems to want companions FOR the clay soliders. I want the clay
soldiers to fight along side me against hostile mobs.

**Comment by GotchaGimmeThanks** [comment]
It seems like a really cool mod :), I've already installed it.

**Comment by SanAndreasP** [comment]
They attacked mobs when you attacked those in previous versions. Since it's still beta and features are missing, you can expect to see this feature back in future iterations.

**Comment by GotchaGimmeThanks** [comment]
very exciting, for now can you point me towards the most recent version I
can use that has this feature?

**Comment by SanAndreasP** [comment]
version (1.)9.1.1 for Minecraft 1.5.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280625-clay-soldiers-mod-v-2-0-0-beta-2

under the spoiler of "Older Downloads"

**Comment by GotchaGimmeThanks** [comment]
Thank you. I am currently enjoying Industrialcraft experimental, so I won't
be stepping back into 1.5, I'll just look forward to clay soliders'
progress :) Thanks again.

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
