### ISSUE TITLE
Refuses to start with cryptic "needle not found in haystack" error on server

### ISSUE THREAD

**Issue by Jaitsu** [SanAndreasP/ClaySoldiersMod#42]
Trying to run a server with a handful of other mods, and recently tried to add Clay Soldiers. However, while loading the SAPManPack library, it crashes silently, and this is in my logs:

http://pastebin.com/PsmvntVu

**Comment by SanAndreasP** [comment]
Cauldron is not supported anymore, since it's discontinued.
