### ISSUE TITLE
When will you fix the building bug 1.7.10

### ISSUE THREAD

**Issue by NoCaption14** [SanAndreasP/ClaySoldiersMod#49]
when will you fix the bug were the clay soldiers don't pick up the wood and build houses on MFL 1.7.10

**Comment by Spartan322** [comment]
#17 It is not a bug, it is due to this mod not being the same code as the original mod, so they had to rewrite everything so it is not implemented yet.

**Comment by CliffracerX** [comment]
Mod was rewritten, building isn't added yet.
