### ISSUE TITLE
1.8 forge is out!

### ISSUE THREAD

**Issue by cjm4001** [SanAndreasP/ClaySoldiersMod#50]
Are you going to update this mod to 1.8 forge?

**Comment by Spartan322** [comment]
It's probably better until more of the request features are in before that happens.

**Comment by cjm4001** [comment]
Makes sense. Love this mod!

**Comment by CliffracerX** [comment]
No updates to 1.8 for a while yet, want to get the 1.7 release stable and about to where the 1.5 and before releases were in terms of features.

**Comment by SanAndreasP** [comment]
Closing this. It's updating when it's ready for it.
