### ISSUE TITLE
items dont break plus infinite shooting

### ISSUE THREAD

**Issue by po123po** [SanAndreasP/ClaySoldiersMod#55]
I have suggested infinite shooting before and u said it causes disadvantage to melee soldiers but if u also make items not breaking
and also just like a bow enchanted with infinite they could shoot infinitely

games like lol and dota, weapons never break

**Comment by CliffracerX** [comment]
May be able to do this as a config option, will look into it at some point.

**Comment by po123po** [comment]
thx very much

**Comment by SanAndreasP** [comment]
whoops, accidentally closed this in a commit... sorry :(

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
