### ISSUE TITLE
the king crowded

### ISSUE THREAD

**Issue by ShadowSide2** [SanAndreasP/ClaySoldiersMod#58]
What u should change is instead of everyone rushing the king he should only have a certain type of clay soldier follow him. The clay soldier should change into a clay soldier that will follow the king by giving him an item so that when that clay soldier picks up that item he will hone in on the king and follow him and thus they would be the king's "guard" and another item like the disruptor that can set all clay soldiers to follow the king or set it to only the guards follow the king or no one follow the king. The guards should also more HP and attack damage than any other clay soldier with any upgrade. The guards should also have a set cap like a max of 10 king guards so not to have OP fights that last forever.  The clay soldiers should also only be able to pick up the item that turns them into king guards if there is a king. And when the king dies the guards should get sometype of poison/weakness/slowness effect.

**Comment by CliffracerX** [comment]
Normal kings are likely to remain the same, or perhaps this will become configurable.  Easiest solution would be to have a different type of Clay Soldier for these king battles.

**Comment by MBTshock** [comment]
yea the clay soldiers don't pick up any item or mounts when they r following the king. Speaking of Mounts the turtle don't show up in the statistics display (Basicly nothing but I just wanted  to point it out)

LOVE THIS MOD!!!

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
