### ISSUE TITLE
Manager Not Being Recognized

### ISSUE THREAD

**Issue by Garey77** [SanAndreasP/ClaySoldiersMod#60]
My forge isn't recognizing the the Manager Pack. Updated Forge, Java, and tried all versions and variations of the Manager... Still not working.

I'm not crashing, I get a brown screen saying (The image attached):

Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
sapmanpack : minimum version required is 2.4.0
The file 'ForgeModLoader-client-0.log' contains more information.
![635612065490882371](https://cloud.githubusercontent.com/assets/11398417/6566544/3b941fc8-c691-11e4-8a02-9fb9296f2771.png)

I'm using version 2.4.1, i've tried 2.4.0, and i'm still getting the same message on Java 8, and forge 1291. I've even tried old versions of the mod, and it's manager. The only thing that changes is the required manager name.

**Comment by SanAndreasP** [comment]
Logs

**Comment by Garey77** [comment]
I set a marker on my logs, added the mods, launched the game, refreshed the logs, and nothing new came up.
![screen shot 2015-03-16 at 4 35 07 pm](https://cloud.githubusercontent.com/assets/11398417/6675928/913db27c-cbfa-11e4-83ea-0eadd2d2e87e.png)

**Comment by Garey77** [comment]
I'm on an iMac, and I'm telling you that your corepack isn't registering as a mod, for whatever reason.

**Comment by Garey77** [comment]
This is a picture of my mods folder, if you do not believe me.
![screen shot 2015-03-16 at 4 38 15 pm](https://cloud.githubusercontent.com/assets/11398417/6675992/eaffc656-cbfa-11e4-8d8e-6fec700d41da.png)

**Comment by SanAndreasP** [comment]
Can you post the fml-client-latest.log? It's in .minecraft/logs
And please use http://gist.github.com to post it.

**Comment by Garey77** [comment]
Not totally familiar with this cite, but here's the URL for the logs I just entered in the link you gave me.

Both of them take me to the logs when I copy and paste them into the search bar.

https://gist.github.com/Garey77/d833428fc9d9609214c9#file-gistfile1-txt

https://gist.github.com/Garey77/d833428fc9d9609214c9

**Comment by Garey77** [comment]
Also, the entries from the first few seconds, I don't think are on there. It wouldn't let me scroll up any more.

And thanks for taking the time to do this.

**Comment by SanAndreasP** [comment]
I can already spot the error:
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.10.2, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

Your Minecraft uses Java 6. See #23

**Comment by Garey77** [comment]
Thank you so much. I already had Java 8 installed, but I redid it, and it still didn't work. I tried 7, and the same thing. The logs look a little different, but it still says that i'm using Java 6. When I check the Java cite, and my computer, they both say Java 8, or 7, and but when I ender the Terminal Command on #23 and the logs, it still says Java version 1.6. Anything you can suggest, because that thread on 23 hasn't shown anything I can use. I'll upload Logs in a sec.

**Comment by Garey77** [comment]
Logs:

https://gist.github.com/Garey77/2a9a1f2ded54a7ba01a1

**Comment by SanAndreasP** [comment]
You've tried the tutorial I've linked there?
Also it doesn't seem to load my coremod at all, which is odd. Where did you put it?

**Comment by Garey77** [comment]
This is my forge profile settings.

And it's in my Mods folder, like in the image above.

![screen shot 2015-03-19 at 6 21 45 pm](https://cloud.githubusercontent.com/assets/11398417/6742280/db7a1774-ce64-11e4-8956-59c0937c7740.png)

**Comment by SanAndreasP** [comment]
Yea, set the Executable path like described in the tutorial.

**Comment by Garey77** [comment]
When I do it, Forge and Vanilla won't even work, and I had to re download the launcher.

**Comment by Garey77** [comment]
This is what my Terminal says when I search for the destination for the executable.

But my computer says I have Java 8.

![screen shot 2015-03-19 at 8 19 29 pm](https://cloud.githubusercontent.com/assets/11398417/6743809/4e8a5de0-ce75-11e4-8826-a5c34af74c41.png)


![screen shot 2015-03-19 at 8 18 43 pm](https://cloud.githubusercontent.com/assets/11398417/6743802/2b604fbe-ce75-11e4-90a1-fc9abe511c05.png)

**Comment by Garey77** [comment]
I just tried coping the Path in the above screenshot into Executables, and it still didn't work. I still get the "no manager installed" screen.

**Comment by SanAndreasP** [comment]
Looking back at your mods screenshot, are these folders?

**Comment by Garey77** [comment]
Yea. I'm on a Mac, you're supposed to use folders for mods. (I've used mods before, I know how to use them)

**Comment by SanAndreasP** [comment]
no, you are supposed to put the jar file into the mods folder, like for everything else.
That's why it can't load my coremod.

What you can do is make a subfolder called "1.7.10" and put the jar files in there, so it will only load those mods for that minecraft version.

**Comment by Garey77** [comment]
IT WORKS!!!! :D 
![screen shot 2015-03-22 at 1 27 09 pm](https://cloud.githubusercontent.com/assets/11398417/6770469/34788b6a-d097-11e4-93a5-50811aef9122.png)


That's exactly what was wrong. Thank you soooooo much!

The mod itself is still a folder, but i reverted the modpack to .jar, and it worked. iMac's are so picky.
![screen shot 2015-03-22 at 1 26 03 pm](https://cloud.githubusercontent.com/assets/11398417/6770464/02e6b6a8-d097-11e4-8370-388974b90aa7.png)

**Comment by Garey77** [comment]
You're awesome. Thanks sooooo much.

**Comment by SanAndreasP** [comment]
yea, by the way, mods aren't supposed to be folders either. Why it works I don't know...
So I suggest renaming that folder as well

**Comment by Garey77** [comment]
Watch any Tutorial for a Mac, you're supposed to convert .jar to .zip, then unzip.

Most of my mods don't work in .jar or .zip form, that's why I was having so much trouble with this.

Anyways, thanks again.
