### ISSUE TITLE
Issue with Dispensers

### ISSUE THREAD

**Issue by Tschipp** [SanAndreasP/ClaySoldiersMod#68]
Soldiers get deployed by Dispensers, but Mounts don't (I only tested it with dirt Horses). Also if you kill a soldier spawned from a dispenser, they don't get dropped.

**Comment by Alejandroibo** [comment]
for me, they never get dropped

**Comment by Spartan322** [comment]
I don't think the mount items have dispense behavior implemented yet.

**Comment by SanAndreasP** [comment]
Forgot to close this, I accidentially switched numbers around in the commit message :(

Here's the commit:
134bfee
