### ISSUE TITLE
Clay Cam

### ISSUE THREAD

**Issue by NeverLoseGuy** [SanAndreasP/ClaySoldiersMod#70]
Here's what I experienced : When on clay cam, it will make lots of step sound rapidly e.g. if you're on grass, it will make a lot of grass sound.

I also got 2 suggestions :
1. First person clay cam. It might be cool to see a soldier fight with others in our eyes during battle.
2. Clay inventory. When in clay cam, you can access its inventory by pressing E just like when you open yours. This can put in and take out items from soldiers specifically without accidently give it to others.

**Comment by CliffracerX** [comment]
The step sound thing I'm not sure how to fix, but the first-person clay cam used to be a thing.

The inventory?  That would actually be great, will look into adding that at some point.

**Comment by whitepik101** [comment]
great idea I could help design the gui :)

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
