### ISSUE TITLE
I have a bug

### ISSUE THREAD

**Issue by ballparkminerer** [SanAndreasP/ClaySoldiersMod#72]
i have a bug because when i download and install the 1.7.10 version when i try to play it says forge mod loader has found a problem with your minecraft installation the mod and versions listed below could not be found sapmanpack : minimum version required is 2.4.0 the file 'forgemodloader-clien-0.log' contains more information so 1 i dont even know what sapmanpack is 2 there is no forgemodloader-clien-0.log so im confused and i don't know what to do but still i can't play my game with the mod and i need help

**Comment by SanAndreasP** [comment]
See #73
