### ISSUE TITLE
Clay Soldiers Mod

### ISSUE THREAD

**Issue by abel1717** [SanAndreasP/ClaySoldiersMod#81]
Hello everyone, I'm pretty new. I'm trying to load a mod and was following some instructions which told me to download Minecraft Forge..which I did and it worked. I then followed the next instructions that told me to download  Pack Manager and put it in the mods folder and then downlaod the mod and put it in the mods folder also. When I do this, minecraft doesn't work. When I remove the .jars out the folder it works again. Help is appreciated.

The game output log can be seen at: http://paste.ubuntu.com/10889950/

Thanks!

**Comment by CliffracerX** [comment]
This mod isn't 1.8 yet.  Use the 1.7 version of Forge.
