### ISSUE TITLE
Clay Soldiers Mod

### ISSUE THREAD

**Issue by abel1717** [SanAndreasP/ClaySoldiersMod#82]
Hello Everyone, 

I'm trying to load the Clay Soldiers Mod but having some issues. Please see link for the crash report details: http://paste.ubuntu.com/10903764/  

Also see Game Output at: http://paste.ubuntu.com/10903794/

Any help would be appreciated. Thanks in advance.

Abel

**Comment by Spartan322** [comment]
Please install the SAPManagerPack
https://github.com/SanAndreasP/SAPManagerPack/blob/master/releases/1.7.10/SAPManPack-1.7.10-2.1.0.jar?raw=true

**Comment by SanAndreasP** [comment]
Incorrect version of the Manager Pack installed. use the latest version
