### ISSUE TITLE
why theres no item (the soldier, not the weapon and other things) of the soldiers when they die?

### ISSUE THREAD

**Issue by Alejandroibo** [SanAndreasP/ClaySoldiersMod#85]
When a soldier dies theres no clay soldier item, the things he had are there, but the soldier item not,  its a bug? or its from the update? because if its from the update the clay ability is useless, unless you drop like a maniac the clay soldier item.

(sorry for my bad english)

**Comment by CliffracerX** [comment]
Don't make duplicate issues, please.
