### ISSUE TITLE
why when the soldiers die, they dont get dropped?

### ISSUE THREAD

**Issue by Alejandroibo** [SanAndreasP/ClaySoldiersMod#86]
when they died the only thing that appears are the items, not the body (clay soldier item) its this a bug? or its from an update?, because if this is from and update, then he should remove the clay ability to revive the dead ally soldiers

**Comment by Spartan322** [comment]
Um, what do you mean by they don't drop, what do you do to get this "bug"?

**Comment by Alejandroibo** [comment]
The soldier, when he dies, the only thing that appears are the weapons and stuff of that soldier, but the soldier itself dosent,i mean you spawn a soldier, someone kill it and nothing, just weapons, no soldier, they disappear of existence when they die.

**Comment by CliffracerX** [comment]
They never dropped their body in a fancy death animation. They only ever dropped items.

**Comment by maz09mohanad** [comment]
That's not what he meant, he meant the clay soldier item itself getting dropped rather than just their gear.
I.E. when a clay soldier dies, you can't pick up their body and put them back in battle again.
