### ISSUE TITLE
Game isn't launching

### ISSUE THREAD

**Issue by bronzeclown** [SanAndreasP/ClaySoldiersMod#90]
So my game isn't launching with SAPmanpack. I have the latest java and run on windows so I have no idea what's wrong. it does this even if I remove all other mods.

log:
https://gist.github.com/bronzeclown/4ad0fa417fc1293f91ea
also early startup in case that is important:
https://gist.github.com/bronzeclown/b4aa7fb808aa0a3aedb4

**Comment by Spartan322** [comment]
hmm, if it seems like SAPmanpack issue it should go [here](https://github.com/SanAndreasP/SAPManagerPack/issues) but why is the horse entity class being modified, seems like forge but if so it should have crashed a lot sooner. Not sure the issue otherwise.

**Comment by bronzeclown** [comment]
pulled them from the directory. Goes directly from the launcher to desktop when it crashes. the game works if I have other mods and no sapmanpack. Only Sapmanpack and the game stops working. I could drop off a log with only sapmanpack installed if that would help, but it's about the same size

**Comment by Spartan322** [comment]
appears SAPmanpack is trying to access a non-existent class, try reinstalling forge, all I can recommend

**Comment by bronzeclown** [comment]
yeah it was forge, thank you for your help

**Comment by SanAndreasP** [comment]
To clarify: The Manager Pack modifies the horse in order for me to allow custom horse armor.
