### ISSUE TITLE
My Game Is automatically crashing!

### ISSUE THREAD

**Issue by ariesrae** [SanAndreasP/ClaySoldiersMod#96]
![sad_pug](https://cloud.githubusercontent.com/assets/12889511/8153147/ce899496-12dd-11e5-91df-7934c44ead98.jpg)
hey guys, my game when I start it is automatically crashing. does anyone know how to fix it?

**Comment by SanAndreasP** [comment]
Logs or I'll close this.
HINT: They're in logs/fml-client-latest.log, please use http://gist.github.com to post them here

**Comment by ariesrae** [comment]
https://gist.github.com/ariesrae/5fe2f1e34f5cd340767e

**Comment by ariesrae** [comment]
I remember seeing that you need Java 7 to run it but how do I find out what version of Java I Have?

**Comment by Spartan322** [comment]
It seems like you are missing certain SAP Manager Pack files, I'm not sure if that is the issue but maybe re-downloading the SAP Man Pack (that's the best I've got)

**Comment by ariesrae** [comment]
ok thankyou

**Comment by ariesrae** [comment]
that didnt work... =(

**Comment by SanAndreasP** [comment]
<tt>C:\Documents and Settings\[...]\Application Data\.minecraft\Clay Soldiers (The system cannot find the file specified)</tt>
uhm... how did you install the mods?
Please provide exact steps.

BTW, you have Java 8, so you're good to go on that part:
<tt>Java is Java HotSpot(TM) Client VM, version 1.8.0_25</tt>

**Comment by ariesrae** [comment]
I got it working so you can close this if you want
