### ISSUE TITLE
Cauldron Crash

### ISSUE THREAD

**Issue by voidswrath** [SanAndreasP/ClaySoldiersMod#97]
Could be a cauldron bug?

18.06 13:46:22 [Multicraft] Not restarting crashed server.
18.06 13:46:22 [Multicraft] Server stopped
18.06 13:46:22 [Multicraft] Looks like a crash, check the server console. Return value: 1
18.06 13:46:22 [Multicraft] Server shut down
18.06 13:46:22 [Server] INFO ... 15 more
18.06 13:46:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174)
18.06 13:46:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276)
18.06 13:46:22 [Server] INFO at de.sanandrew.core.manpack.transformer.TransformPlayerDismountCtrl.transform(TransformPlayerDismountCtrl.java:30)
18.06 13:46:22 [Server] INFO at de.sanandrew.core.manpack.transformer.TransformPlayerDismountCtrl.transformPlayer(TransformPlayerDismountCtrl.java:73)
18.06 13:46:22 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.tree.MethodInsnNode.<init>(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
18.06 13:46:22 [Server] INFO ... 13 more
18.06 13:46:22 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
18.06 13:46:22 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
18.06 13:46:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
18.06 13:46:22 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
18.06 13:46:22 [Server] INFO ... 6 more
18.06 13:46:22 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
18.06 13:46:22 [Server] INFO at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
18.06 13:46:22 [Server] INFO at java.lang.Class.getMethod(Class.java:1784)
18.06 13:46:22 [Server] INFO at java.lang.Class.getMethod0(Class.java:3018)
18.06 13:46:22 [Server] INFO at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
18.06 13:46:22 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
18.06 13:46:22 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method)
18.06 13:46:22 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
18.06 13:46:22 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
18.06 13:46:22 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
18.06 13:46:22 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497)
18.06 13:46:22 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.06 13:46:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18.06 13:46:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.06 13:46:22 [Server] INFO A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
18.06 13:46:09 [Multicraft] Loaded config for "Cauldron 1.7.10 Recommended 1.1207.01.195"
18.06 13:46:09 [Multicraft] Starting server!
18.06 13:46:09 [Multicraft] Loading server properties

**Comment by SanAndreasP** [comment]
provide full logs (logs/fml-server-latest.log) via http://gist.github.com

**Comment by CliffracerX** [comment]
Looks like the wrong version of Forge or SapManPack.  Have you made sure that it's also erroring in CSM/SapManPack and not something else you have installed?

**Comment by SanAndreasP** [comment]
From your short crash log I see it's not finding a method from the ObjectWeb ASM library, indicating your Cauldron version uses an outdated Forge version...
Maybe try this version, as I've used it to test my ManagerPack on while fixing that other cauldron crash, and has a supported Forge version: https://prok.pw/gitlab/Prototik/KCauldron/tree/master

**Comment by SanAndreasP** [comment]
Closing this now. If you still have problems, open up a new issue.
